
import { WordData } from './types';

export const LEVEL_1_DATA: WordData[] = [
  /* BLOQUE 1 (1-20) */
  { "id": "1-1", "hitza": "antzeman", "sinonimoak": ["igarri", "nabaritu", "sumatu", "konturatu", "ohartu"] },
  { "id": "1-2", "hitza": "izutu", "sinonimoak": ["beldurtu", "ikaratu", "kikildu", "oilotu", "koldartu"] },
  { "id": "1-3", "hitza": "hizki", "sinonimoak": ["letra"] },
  { "id": "1-4", "hitza": "ulergaitz", "sinonimoak": ["ulertezin", "adiezin", "adigaitz"] },
  { "id": "1-5", "hitza": "suspertu", "sinonimoak": ["indarberritu"] },
  { "id": "1-6", "hitza": "igorri", "sinonimoak": ["bidali"] },
  { "id": "1-7", "hitza": "zeken", "sinonimoak": ["esku-labur", "zikoitz", "eskulabur"] },
  { "id": "1-8", "hitza": "jakiteko grina", "sinonimoak": ["jakin-min", "jakingura", "jakin-gose", "jakin-nahi"] },
  { "id": "1-9", "hitza": "are gehiago", "sinonimoak": ["areago"] },
  { "id": "1-10", "hitza": "leize", "sinonimoak": ["kobazulo", "haitzulo"] },
  { "id": "1-11", "hitza": "eremu", "sinonimoak": ["alor", "arlo", "esparru", "sail"] },
  { "id": "1-12", "hitza": "hondar", "sinonimoak": ["harea", "hondakin"] },
  { "id": "1-13", "hitza": "gauzatu", "sinonimoak": ["burutu"] },
  { "id": "1-14", "hitza": "esanahi", "sinonimoak": ["esangura", "adiera", "esankizun"] },
  { "id": "1-15", "hitza": "lapurtu", "sinonimoak": ["ostu", "ebatsi"] },
  { "id": "1-16", "hitza": "ahaztu", "sinonimoak": ["ahantzi"] },
  { "id": "1-17", "hitza": "aditzera eman", "sinonimoak": ["jakinarazi", "ezagutarazi", "adierazi"] },
  { "id": "1-18", "hitza": "bestela", "sinonimoak": ["osterantzean", "gainerakoan"] },
  { "id": "1-19", "hitza": "nagusitasun", "sinonimoak": ["gailentasun", "gehiagotasun"] },
  { "id": "1-20", "hitza": "oinatz", "sinonimoak": ["arrasto", "aztarna"] },

  /* BLOQUE 2 (21-40) */
  { "id": "1-21", "hitza": "aztarna", "sinonimoak": ["arrasto", "oinatz"] },
  { "id": "1-22", "hitza": "lohitu", "sinonimoak": ["zikindu", "likistu", "txerritu", "mantxatu"] },
  { "id": "1-23", "hitza": "jazo", "sinonimoak": ["gertatu"] },
  { "id": "1-24", "hitza": "iskanbila", "sinonimoak": ["astrapala", "zalaparta", "zarraparra"] },
  { "id": "1-25", "hitza": "ikuzi", "sinonimoak": ["garbitu", "txukundu", "xahutu", "araztu"] },
  { "id": "1-26", "hitza": "nabarmendu", "sinonimoak": ["nagusitu", "gailendu", "gailurtu"] },
  { "id": "1-27", "hitza": "gizendu", "sinonimoak": ["loditu", "guritu", "marduldu", "galantu", "mardotu"] },
  { "id": "1-28", "hitza": "sustraitu", "sinonimoak": ["errotu", "erroak bota"] },
  { "id": "1-29", "hitza": "martxan jarri", "sinonimoak": ["abiarazi", "abian jarri"] },
  { "id": "1-30", "hitza": "edozenbat", "sinonimoak": ["nahi beste", "nahi adina", "gura adina"] },
  { "id": "1-31", "hitza": "miresmen", "sinonimoak": ["gurtza"] },
  { "id": "1-32", "hitza": "entzun", "sinonimoak": ["aditu"] },
  { "id": "1-33", "hitza": "ulertu", "sinonimoak": ["aditu", "jabetu"] },
  { "id": "1-34", "hitza": "ezelango", "sinonimoak": ["inola"] },
  { "id": "1-35", "hitza": "zaratatsua", "sinonimoak": ["arramatsu", "astrapalatsu"] },
  { "id": "1-36", "hitza": "oztopoa", "sinonimoak": ["destorbu", "eragozpen", "traba"] },
  { "id": "1-37", "hitza": "munstro", "sinonimoak": ["piztia"] },
  { "id": "1-38", "hitza": "heldu", "sinonimoak": ["eutsi", "oratu", "lotu"] },
  { "id": "1-39", "hitza": "iritsi", "sinonimoak": ["ailegatu", "erdutu", "heldu"] },
  { "id": "1-40", "hitza": "hurko", "sinonimoak": ["hurbileko", "aldeko"] },

  /* BLOQUE 2 (41-60) */
  { "id": "1-41", "hitza": "hurko", "sinonimoak": ["hurbileko", "aldeko"] },
  { "id": "1-42", "hitza": "kartela", "sinonimoak": ["afixa", "idazkun"] },
  { "id": "1-43", "hitza": "arerioa", "sinonimoak": ["etsai", "aurkari", "izterbegi"] },
  { "id": "1-44", "hitza": "suertatu", "sinonimoak": ["gertatu", "jazo"] },
  { "id": "1-45", "hitza": "hurbildu", "sinonimoak": ["hurreratu", "gerturatu"] },
  { "id": "1-46", "hitza": "ekidin", "sinonimoak": ["saihestu"] },
  { "id": "1-47", "hitza": "atzaparra", "sinonimoak": ["erpe", "atzamar"] },
  { "id": "1-48", "hitza": "seko", "sinonimoak": ["guztiz", "zeharo", "total", "erabat"] },
  { "id": "1-49", "hitza": "hanka", "sinonimoak": ["zango", "berna", "izter"] },
  { "id": "1-50", "hitza": "berna", "sinonimoak": ["zangosagar", "aztal", "zangar"] },
  { "id": "1-51", "hitza": "jin", "sinonimoak": ["etorri"] },
  { "id": "1-52", "hitza": "irla", "sinonimoak": ["uharte"] },
  { "id": "1-53", "hitza": "oroitu", "sinonimoak": ["gogoratu", "gomutatu", "gogoan izan"] },
  { "id": "1-54", "hitza": "izaera", "sinonimoak": ["aiurri", "nortasun", "seta"] },
  { "id": "1-55", "hitza": "gaitzetsi", "sinonimoak": ["ezetsi", "hastandu"] },
  { "id": "1-56", "hitza": "ortu", "sinonimoak": ["baratze"] },
  { "id": "1-57", "hitza": "eltze", "sinonimoak": ["lapiko", "tupina"] },
  { "id": "1-58", "hitza": "kapela", "sinonimoak": ["txano"] },
  { "id": "1-59", "hitza": "mediku", "sinonimoak": ["sendagile", "osagile", "osatzaile"] },
  { "id": "1-60", "hitza": "oski", "sinonimoak": ["zapata"] },
  

  /* BLOQUE 2 (61-80) */
  { "id": "1-61", "hitza": "goraintzi", "sinonimoak": ["eskumuin"] },
  { "id": "1-62", "hitza": "zama", "sinonimoak": ["karga", "haxe"] },
  { "id": "1-63", "hitza": "eserleku", "sinonimoak": ["jarleku", "jesarleku", "esertoki"] },
  { "id": "1-64", "hitza": "arraro", "sinonimoak": ["bitxi", "arrotz"] },
  { "id": "1-65", "hitza": "ezezaguna", "sinonimoak": ["arrotz"] },
  { "id": "1-66", "hitza": "familia", "sinonimoak": ["sendi", "senitarte"] },
  { "id": "1-67", "hitza": "ezkutatu", "sinonimoak": ["ostendu"] },
  { "id": "1-68", "hitza": "hondatu", "sinonimoak": ["suntsitu", "erraustu", "txikitu"] },
  { "id": "1-69", "hitza": "beti", "sinonimoak": ["betiere", "aldiro", "une oro", "aldi oro"] },
  { "id": "1-70", "hitza": "salto egin", "sinonimoak": ["jauzi egin", "saltatu"] },
  { "id": "1-71", "hitza": "begiratu", "sinonimoak": ["behatu", "so egin"] },
  { "id": "1-72", "hitza": "indarkeria", "sinonimoak": ["bortxakeria", "gogorkeria", "biolentzia"] },
  { "id": "1-73", "hitza": "bide batez", "sinonimoak": ["bidenabar", "bidez"] },
  { "id": "1-74", "hitza": "hozbero", "sinonimoak": ["tenperatura"] },
  { "id": "1-75", "hitza": "sargori", "sinonimoak": ["sapa", "lanbero"] },
  { "id": "1-76", "hitza": "umel", "sinonimoak": ["heze", "ezko", "busti"] },
  { "id": "1-77", "hitza": "erauzi", "sinonimoak": ["kendu", "idoki"] },
  { "id": "1-78", "hitza": "oihartzun", "sinonimoak": ["durundi"] },
  { "id": "1-79", "hitza": "galbideratu", "sinonimoak": ["perbertitu", "okertu"] },
  { "id": "1-80", "hitza": "gupida", "sinonimoak": ["erruki", "urriki"] },
  
  /* BLOQUE 2 (81-100) */
  { "id": "1-81", "hitza": "inguruabar", "sinonimoak": ["egoera", "zertzelada", "kondizio"] },
  { "id": "1-82", "hitza": "lotsagabe", "sinonimoak": ["lotsabako", "lotsagaldu", "ahalkegabe"] },
  { "id": "1-83", "hitza": "iragarri", "sinonimoak": ["komunikatu", "jakinarazi"] },
  { "id": "1-84", "hitza": "emanaldi", "sinonimoak": ["emankizun", "saio", "emisio"] },
  { "id": "1-85", "hitza": "esamesa", "sinonimoak": ["zurrumurru", "erran-merran", "elepide"] },
  { "id": "1-86", "hitza": "belaunaldi", "sinonimoak": ["gizaldi"] },
  { "id": "1-87", "hitza": "argitaraldi", "sinonimoak": ["argitalpen", "edizio"] },
  { "id": "1-88", "hitza": "gorespen", "sinonimoak": ["goraipamen", "gorazarre", "laudorio", "laudamen"] },
  { "id": "1-89", "hitza": "biziraute", "sinonimoak": ["biziraupen"] },
  { "id": "1-90", "hitza": "kaskartu", "sinonimoak": ["txartu", "okerragotu", "gaizkoatu"] },
  { "id": "1-91", "hitza": "ezkontide", "sinonimoak": ["ezkonlagun", "bizikide", "bizilagun"] },
  { "id": "1-92", "hitza": "deitoratu", "sinonimoak": ["auhendatu", "adiakatu", "tamaldu", "penatu"] },
  { "id": "1-93", "hitza": "berau", "sinonimoak": ["hauxe", "hau bera"] },
  { "id": "1-94", "hitza": "sastakatu", "sinonimoak": ["sastatu", "aiztoa sartu"] },
  { "id": "1-95", "hitza": "emagaldu", "sinonimoak": ["ematxar", "urdanga", "maritzar", "julis", "bordion"] },
  { "id": "1-96", "hitza": "zoroetxe", "sinonimoak": ["eroetxe", "erotegi"] },
  { "id": "1-97", "hitza": "biziraupen", "sinonimoak": ["biziraute"] },
  { "id": "1-98", "hitza": "burrunba", "sinonimoak": ["danbada", "dunbots", "danbateko"] },
  { "id": "1-99", "hitza": "jalgi", "sinonimoak": ["atera", "ilki"] },
  { "id": "1-100", "hitza": "iaio", "sinonimoak": ["trebe", "abil", "artetsu"] },
  
  /* BLOQUE 2 (101-120) */
  { "id": "1-101", "hitza": "kimatu", "sinonimoak": ["inausi", "adaondu", "moztu"] },
  { "id": "1-102", "hitza": "lehortu", "sinonimoak": ["ihartu", "sikatu", "kabartu"] },
  { "id": "1-103", "hitza": "gogaikarri", "sinonimoak": ["nekagarri", "nekoso", "aspergarri"] },
  { "id": "1-104", "hitza": "ugazaba", "sinonimoak": ["etxejabe", "nagusi", "patroi"] },
  { "id": "1-105", "hitza": "gizatalde", "sinonimoak": ["talde", "kolektibo"] },
  { "id": "1-106", "hitza": "burujabetza", "sinonimoak": ["subiranotasun", "berjabetasun"] },
  { "id": "1-107", "hitza": "sinatu", "sinonimoak": ["izenpetu"] },
  { "id": "1-108", "hitza": "mintzo izan", "sinonimoak": ["hitz egin", "mintzatu", "berba egin", "solas egin"] },
  { "id": "1-109", "hitza": "muzin egin", "sinonimoak": ["mespretxatu", "arbuiatu", "gutxietsi"] },
  { "id": "1-110", "hitza": "oraintsu", "sinonimoak": ["berriki", "oraindik orain"] },
  { "id": "1-111", "hitza": "soil", "sinonimoak": ["xume", "xalo", "laño"] },
  { "id": "1-112", "hitza": "partaidetza", "sinonimoak": ["parte-hartze", "partaidetasun", "esku-harmen"] },
  { "id": "1-113", "hitza": "arrapala", "sinonimoak": ["aldapa", "aldats", "malda", "ike"] },
  { "id": "1-114", "hitza": "narriadura", "sinonimoak": ["degradazio"] },
  { "id": "1-115", "hitza": "ezagutzera eman", "sinonimoak": ["jakinarazi", "ezagutarazi"] },
  { "id": "1-116", "hitza": "matxura", "sinonimoak": ["aberia"] },
  { "id": "1-117", "hitza": "gaitasun", "sinonimoak": ["trebetasun", "trebezia"] },
  { "id": "1-118", "hitza": "herritartasun", "sinonimoak": ["hiritartasun", "hiritargo"] },
  { "id": "1-119", "hitza": "isilaldi", "sinonimoak": ["isilune"] },
  { "id": "1-120", "hitza": "onbideratu", "sinonimoak": ["oneratu"] },
  
  /* BLOQUE 2 (121-140) */
  { "id": "1-121", "hitza": "lelo", "sinonimoak": ["goiburu", "ikurritz", "eslogan"] },
  { "id": "1-122", "hitza": "hara-hona", "sinonimoak": ["batera eta bestera", "gora eta behera", "harat-honat"] },
  { "id": "1-123", "hitza": "tardatu", "sinonimoak": ["berandutu"] },
  { "id": "1-124", "hitza": "zarratu", "sinonimoak": ["itxi", "hetsi", "zerratu"] },
  { "id": "1-125", "hitza": "gainbehera", "sinonimoak": ["dekadentzia", "endekapen"] },
  { "id": "1-126", "hitza": "mamitsu", "sinonimoak": ["sakon", "adierazgarri"] },
  { "id": "1-127", "hitza": "ontasun", "sinonimoak": ["onezia", "onberatasun"] },
  { "id": "1-128", "hitza": "hurkotasun", "sinonimoak": ["hurbiltasun", "gertutasun"] },
  { "id": "1-129", "hitza": "gogorarazi", "sinonimoak": ["burura ekarri", "oroitarazi", "gomutarazi"] },
  { "id": "1-130", "hitza": "haserretu", "sinonimoak": ["sumindu", "muturtu", "koskatu", "zapuztu", "zipoztu"] },
  { "id": "1-131", "hitza": "jakinez", "sinonimoak": ["ezjakintasun", "ezjakite", "ezezgutza"] },
  { "id": "1-132", "hitza": "beharrizan", "sinonimoak": ["behar", "premia", "derrigortasun"] },
  { "id": "1-133", "hitza": "xahutu", "sinonimoak": ["eralgi", "zarrasteldu", "irion", "irazi"] },
  { "id": "1-134", "hitza": "gabetasun", "sinonimoak": ["hutsune", "peitu", "falta"] },
  { "id": "1-135", "hitza": "bermatu", "sinonimoak": ["garantizatu"] },
  { "id": "1-136", "hitza": "anoa", "sinonimoak": ["errazio"] },
  { "id": "1-137", "hitza": "mozkin", "sinonimoak": ["irabazkin", "etekin"] },
  { "id": "1-138", "hitza": "sehaska", "sinonimoak": ["kuma"] },
  { "id": "1-139", "hitza": "berretsi", "sinonimoak": ["konfirmatu"] },
  { "id": "1-140", "hitza": "lagundu", "sinonimoak": ["urgatzi", "sostengatu", "mesede egin", "sorotsi"] },
  
  /* BLOQUE 2 (141-160) */
  { "id": "1-141", "hitza": "sen", "sinonimoak": ["zentzu"] },
  { "id": "1-142", "hitza": "jakitun", "sinonimoak": ["jakintsu"] },
  { "id": "1-143", "hitza": "hurrupa", "sinonimoak": ["trago", "zurrutada", "zurrut", "zirrista"] },
  { "id": "1-144", "hitza": "eragotzi", "sinonimoak": ["galarazi", "oztopo egin", "behaztopatu"] },
  { "id": "1-145", "hitza": "sorrera", "sinonimoak": ["jatorri", "hasiera", "abiapuntu"] },
  { "id": "1-146", "hitza": "itzulikatu", "sinonimoak": ["nahastatu"] },
  { "id": "1-147", "hitza": "izurrite", "sinonimoak": ["izurri", "helde", "epidemia"] },
  { "id": "1-148", "hitza": "sumindu", "sinonimoak": ["berotu", "sutu", "haserretu"] },
  { "id": "1-149", "hitza": "garratz", "sinonimoak": ["gogor"] },
  { "id": "1-150", "hitza": "zartako", "sinonimoak": ["kolpe", "kaska"] },
  { "id": "1-151", "hitza": "jolasti", "sinonimoak": ["jostakin", "jostalari"] },
  { "id": "1-152", "hitza": "uzki", "sinonimoak": ["ipurtzulo"] },
  { "id": "1-153", "hitza": "otsail", "sinonimoak": ["zezeil"] },
  { "id": "1-154", "hitza": "mugarri", "sinonimoak": ["zedarri"] },
  { "id": "1-155", "hitza": "bozka", "sinonimoak": ["botazio", "bozketa", "hauteskunde"] },
  { "id": "1-156", "hitza": "findu", "sinonimoak": ["leundu", "hobetu"] },
  { "id": "1-157", "hitza": "ikusgaitasun", "sinonimoak": ["agerikotasun", "ikusgarritasun"] },
  { "id": "1-158", "hitza": "sariztatu", "sinonimoak": ["saritu"] },
  { "id": "1-159", "hitza": "biritxi", "sinonimoak": ["biki"] },
  { "id": "1-160", "hitza": "xerkatu", "sinonimoak": ["bilatu"] },
  
  /* BLOQUE 2 (161-180) */
  { "id": "1-161", "hitza": "behar-beharrezko", "sinonimoak": ["baitezpadako", "ezinbesteko"] },
  { "id": "1-162", "hitza": "alimaleko", "sinonimoak": ["ikaragarrizko", "izugarrizko"] },
  { "id": "1-163", "hitza": "karrika", "sinonimoak": ["kale"] },
  { "id": "1-164", "hitza": "hizketaldi", "sinonimoak": ["elkarrizketa", "solasaldi", "konbertsazio"] },
  { "id": "1-165", "hitza": "izapide", "sinonimoak": ["tramite", "gestio"] },
  { "id": "1-166", "hitza": "urri", "sinonimoak": ["bakan", "gutxi"] },
  { "id": "1-167", "hitza": "helegite", "sinonimoak": ["apelazio"] },
  { "id": "1-168", "hitza": "ustiatu", "sinonimoak": ["esplotatu"] },
  { "id": "1-169", "hitza": "itsasadar", "sinonimoak": ["errio"] },
  { "id": "1-170", "hitza": "deigarri", "sinonimoak": ["nabarmen"] },
  { "id": "1-171", "hitza": "gizalege", "sinonimoak": ["jokaera", "ibilera"] },
  { "id": "1-172", "hitza": "zeresan", "sinonimoak": ["esamesa", "zurrumurru", "esateko"] },
  { "id": "1-173", "hitza": "zinez", "sinonimoak": ["benetan", "egiatan", "egiaz"] },
  { "id": "1-174", "hitza": "zio", "sinonimoak": ["arrazoi", "zergati"] },
  { "id": "1-175", "hitza": "zital", "sinonimoak": ["gaizto", "ziztrin"] },
  { "id": "1-176", "hitza": "pilare", "sinonimoak": ["zutabe", "habe", "harroin"] },
  { "id": "1-177", "hitza": "pairaezin", "sinonimoak": ["jasanezin", "eramanezin"] },
  { "id": "1-178", "hitza": "ohoin", "sinonimoak": ["ebasle", "lapur"] },
  { "id": "1-179", "hitza": "odolbildu", "sinonimoak": ["odolbatu", "beltzune", "ubeldura"] },
  { "id": "1-180", "hitza": "nahigabe", "sinonimoak": ["atsekabe", "bihozmin", "samin"] },
  
  /* BLOQUE 2 (181-200) */
  { "id": "1-181", "hitza": "lotsati", "sinonimoak": ["herabe", "uzkur"] },
  { "id": "1-182", "hitza": "labainka", "sinonimoak": ["irristaka"] },
  { "id": "1-183", "hitza": "erkatu", "sinonimoak": ["alderatu", "parekatu", "konparatu"] },
  { "id": "1-184", "hitza": "kirri", "sinonimoak": ["hozki", "hozkamin", "tirri"] },
  { "id": "1-185", "hitza": "karan", "sinonimoak": ["eder"] },
  { "id": "1-186", "hitza": "kaiku", "sinonimoak": ["kirten", "lerdo", "kokolo"] },
  { "id": "1-187", "hitza": "jadetsi", "sinonimoak": ["lortu", "erdietsi"] },
  { "id": "1-188", "hitza": "isiotu", "sinonimoak": ["irazeki", "piztu"] },
  { "id": "1-189", "hitza": "iseka", "sinonimoak": ["burla", "trufa", "ihakin"] },
  { "id": "1-190", "hitza": "ildo", "sinonimoak": ["bide", "hari"] },
  { "id": "1-191", "hitza": "hormatu", "sinonimoak": ["izoztu", "jelatu", "leitu"] },
  { "id": "1-192", "hitza": "gomuta", "sinonimoak": ["oroitzapen", "gogorapen", "oroipen"] },
  { "id": "1-193", "hitza": "geriza", "sinonimoak": ["babesa"] },
  { "id": "1-194", "hitza": "ezkila", "sinonimoak": ["kanpaia"] },
  { "id": "1-195", "hitza": "etekin", "sinonimoak": ["mozkin", "hobari"] },
  { "id": "1-196", "hitza": "estakuru", "sinonimoak": ["aitzakia", "apuko"] },
  { "id": "1-197", "hitza": "ereti", "sinonimoak": ["une", "momentu", "lipar", "istant"] },
  { "id": "1-198", "hitza": "arestian", "sinonimoak": ["lehentxeago", "oraintsu", "oixtion"] },
  { "id": "1-199", "hitza": "aratz", "sinonimoak": ["garbi", "garden"] },
  { "id": "1-200", "hitza": "antxeta", "sinonimoak": ["kaio"] },
  
  /* BLOQUE 2 (201-220) */
  { "id": "1-201", "hitza": "ageriko", "sinonimoak": ["bistako", "ezagun"] },
  { "id": "1-202", "hitza": "temoso", "sinonimoak": ["temati", "setati", "muker"] },
  { "id": "1-203", "hitza": "tenore", "sinonimoak": ["garai", "sasoi"] },
  { "id": "1-204", "hitza": "taxutu", "sinonimoak": ["egokitu", "atondu"] },
  { "id": "1-205", "hitza": "taxuzko", "sinonimoak": ["itxurazko", "ganorazko"] },
  { "id": "1-206", "hitza": "usu", "sinonimoak": ["maiz", "sarritan", "askotan"] },
  { "id": "1-207", "hitza": "diosal", "sinonimoak": ["agur", "oles", "salutanzia"] },
  { "id": "1-208", "hitza": "neskazahar", "sinonimoak": ["birrotxa", "mutxurdin"] },
  { "id": "1-209", "hitza": "ezaupide", "sinonimoak": ["ezagutza", "ezaguera"] },
  { "id": "1-210", "hitza": "itomen", "sinonimoak": ["estutasun", "larritasun", "estualdi"] },
  { "id": "1-211", "hitza": "kolpe", "sinonimoak": ["kaska", "talka", "koska", "ukaldi"] },
  { "id": "1-212", "hitza": "bereizgarri", "sinonimoak": ["ezaugarri"] },
  { "id": "1-213", "hitza": "sinestun", "sinonimoak": ["fededun", "sinesle", "sinestedun"] },
  { "id": "1-214", "hitza": "iskin egin", "sinonimoak": ["saihestu", "itzuri", "baztertu"] },
  { "id": "1-215", "hitza": "ezmezean egon", "sinonimoak": ["zalantzan egon"] },
  { "id": "1-216", "hitza": "inozo", "sinonimoak": ["tolesgabe", "bakun", "inozente"] }
];
