import { WordData } from './types';

export const LEVEL_4_PART_5: WordData[] = [
  {"id": "4-401", "hitza": "zango", "sinonimoak": ["hanka", "berna"]},
  {"id": "4-402", "hitza": "zankuts", "sinonimoak": ["oinutsik", "ortozik", "hanka hutsik"]},
  {"id": "4-403", "hitza": "zanpaketa", "sinonimoak": ["zapalkuntza", "errepresioa", "zapalketa"]},
  {"id": "4-404", "hitza": "zaparrada", "sinonimoak": ["indriska", "euri-jasa", "zaldizko"]},
  {"id": "4-405", "hitza": "zaputza", "sinonimoak": ["muzina", "mukerra", "betizua"]},
  {"id": "4-406", "hitza": "zapzipia", "sinonimoak": ["txaplata", "petrala", "pairugabea"]},
  {"id": "4-407", "hitza": "zaramarra", "sinonimoak": ["azantza", "zalaparta", "iskanbila"]},
  {"id": "4-408", "hitza": "zarbaildu", "sinonimoak": ["narriatu", "izorratu", "hondatu"]},
  {"id": "4-409", "hitza": "zarrastelkeria", "sinonimoak": ["xahubidea", "eralketa", "xahutzea"]},
  {"id": "4-410", "hitza": "zatarreria", "sinonimoak": ["zakarreria", "zaborreria", "satarra"]},
  {"id": "4-411", "hitza": "zedarrituak", "sinonimoak": ["finkatuak", "xedatuak", "mugatuak"]},
  {"id": "4-412", "hitza": "zegan", "sinonimoak": ["zenbatean"]},
  {"id": "4-413", "hitza": "zeharka-meharka", "sinonimoak": ["sigi-sagan", "itzulinguruka", "zeharbidez"]},
  {"id": "4-414", "hitza": "zeharretara", "sinonimoak": ["saiheska", "soslaiz", "alboz"]},
  {"id": "4-415", "hitza": "zehatu", "sinonimoak": ["zigortu", "punitu", "gaztigatu"]},
  {"id": "4-416", "hitza": "zekentzea", "sinonimoak": ["zikoiztea", "diruzaletzea", "xuhurztea"]},
  {"id": "4-417", "hitza": "zelaia", "sinonimoak": ["landa", "larre", "belardi"]},
  {"id": "4-418", "hitza": "zelanbait", "sinonimoak": ["nolabait", "nola edo hala", "nolerebait"]},
  {"id": "4-419", "hitza": "zemaitu", "sinonimoak": ["mehatxatu", "larderiatu", "estutu"]},
  {"id": "4-420", "hitza": "zenduaren", "sinonimoak": ["hildakoaren", "hilaren", "defuntuaren"]},
  {"id": "4-421", "hitza": "zentsurarik", "sinonimoak": ["trabarik", "oztoporik", "eragozpenik"]},
  {"id": "4-422", "hitza": "zentzubekeria", "sinonimoak": ["burugabekeria", "erokeria", "burtzrokeria"]},
  {"id": "4-423", "hitza": "zeregin", "sinonimoak": ["eginkizun", "funtzio", "eginbehar"]},
  {"id": "4-424", "hitza": "zergati", "sinonimoak": ["arrazoi", "kari", "zio"]},
  {"id": "4-425", "hitza": "zerikusia", "sinonimoak": ["harremana", "lotura", "erlazioa"]},
  {"id": "4-426", "hitza": "zerraldo", "sinonimoak": ["siku", "ziplo", "blaus"]},
  {"id": "4-427", "hitza": "zerrepeldu", "sinonimoak": ["hotzildu", "epeldu", "hoztu"]},
  {"id": "4-428", "hitza": "zertzeladei", "sinonimoak": ["zehaztasunei", "xehetasunei", "xehadurei"]},
  {"id": "4-429", "hitza": "zeruertzean", "sinonimoak": ["zerumugan", "ostertzean", "hodeiertzean"]},
  {"id": "4-430", "hitza": "zibilizatu", "sinonimoak": ["hezi", "jendetu"]},
  {"id": "4-431", "hitza": "zihoa", "sinonimoak": ["gantza", "urina", "bilgorra"]},
  {"id": "4-432", "hitza": "zikiratu", "sinonimoak": ["irendu", "irantzi"]},
  {"id": "4-433", "hitza": "zildaia", "sinonimoak": ["muturrekoa", "mozala"]},
  {"id": "4-434", "hitza": "zilegitzeko", "sinonimoak": ["baimentzeko", "onartzeko", "onesteko"]},
  {"id": "4-435", "hitza": "zimarkua", "sinonimoak": ["iruzurra", "amarrua", "jukutria"]},
  {"id": "4-436", "hitza": "zimiko", "sinonimoak": ["imurtxi", "atximur(ka)", "txatxamur(ka)"]},
  {"id": "4-437", "hitza": "zimurkera", "sinonimoak": ["diruzalekeria", "zekenkera", "zuhurrkeria"]},
  {"id": "4-438", "hitza": "zin-zinez", "sinonimoak": ["bene-benetan", "zinez eta minez", "egia-egitan"]},
  {"id": "4-439", "hitza": "zindoa", "sinonimoak": ["langilea", "fina", "ondradua"]},
  {"id": "4-440", "hitza": "zinemaratu", "sinonimoak": ["pantailaratu", "proiektatu", "filmarazi"]},
  {"id": "4-441", "hitza": "zintzotasunez", "sinonimoak": ["onestasunez", "prestutasunez", "ondradutasunez"]},
  {"id": "4-442", "hitza": "zintzurkoia", "sinonimoak": ["jatuna", "tripontzia", "salobrea"]},
  {"id": "4-443", "hitza": "zintzurluenak", "sinonimoak": ["ahozuriak", "mokofinak"]},
  {"id": "4-444", "hitza": "zira", "sinonimoak": ["kapusaia", "anoraka"]},
  {"id": "4-445", "hitza": "zirikatzen", "sinonimoak": ["xaxatzen", "ahakatzen", "probokatzen"]},
  {"id": "4-446", "hitza": "zirko", "sinonimoak": ["extarte", "kalezulo", "sohorna"]},
  {"id": "4-447", "hitza": "zirpildua", "sinonimoak": ["listua", "altsitua", "pirukatua"]},
  {"id": "4-448", "hitza": "zirrara", "sinonimoak": ["hunkipen", "sentsazio", "zarrasta"]},
  {"id": "4-449", "hitza": "zirtzileriak", "sinonimoak": ["purtzilkeriak", "zizki-mizkiak", "huskeriak"]},
  {"id": "4-450", "hitza": "ziurrenik", "sinonimoak": ["ziur aski", "asko", "segurutik", "segur aski"]},
  {"id": "4-451", "hitza": "zizini", "sinonimoak": ["asmo", "xede", "uste"]},
  {"id": "4-452", "hitza": "ziztrin", "sinonimoak": ["txatxar", "hutsal", "purtzil"]},
  {"id": "4-453", "hitza": "zokoratzen", "sinonimoak": ["bazterreratzen", "alboratzen", "baztertzen"]},
  {"id": "4-454", "hitza": "zoli", "sinonimoak": ["adi", "erne", "arretatsu"]},
  {"id": "4-455", "hitza": "zoratzeko", "sinonimoak": ["erotzeko", "txoratzeko", "burutik egiteko"]},
  {"id": "4-456", "hitza": "zoritzarrekoa", "sinonimoak": ["zorigabekoa", "zorigaiztokoa", "zorigaiztekoa"]},
  {"id": "4-457", "hitza": "zorritsoz", "sinonimoak": ["zorritsuz", "zikinez", "koipeztoz"]},
  {"id": "4-458", "hitza": "zorrotzazun", "sinonimoak": ["gogortasun", "zurruntasun", "irmotasun"]},
  {"id": "4-459", "hitza": "zozotu", "sinonimoak": ["txepeldu", "totolotu", "memelotu"]},
  {"id": "4-460", "hitza": "zubiototik", "sinonimoak": ["zaldainetik", "pasagunetik", "pasabidetik"]},
  {"id": "4-461", "hitza": "zuhaitzi", "sinonimoak": ["arboladi", "baso", "oihan"]},
  {"id": "4-462", "hitza": "zulatzeak", "sinonimoak": ["indusketak", "hondaketak", "prospekzioas"]},
  {"id": "4-463", "hitza": "zurikeriaka", "sinonimoak": ["losintxaka", "lausenguka", "balakuka"]},
  {"id": "4-464", "hitza": "zurmindu", "sinonimoak": ["sorgortu", "hozmindu", "gogortu"]},
  {"id": "4-465", "hitza": "zurturik", "sinonimoak": ["harriturik", "txunditurik", "espantaturik"]},
  {"id": "4-466", "hitza": "zutundu", "sinonimoak": ["zutitu", "altxatu", "jaiki"]},
  {"id": "4-467", "hitza": "zutzarturik", "sinonimoak": ["sustraiturik", "erroturik", "bertakoturik"]},
  {"id": "4-468", "hitza": "zuzeneko", "sinonimoak": ["artez"]}
];