import { WordData } from './types';

export const LEVEL_2_PART_1: WordData[] = [
  /* BLOQUE 1 (1-20) */
  {"id": "2-1", "hitza": "abaraska", "sinonimoak": ["orraze", "abao", "ezti-orraze"]},
  {"id": "2-2", "hitza": "abiapuntu", "sinonimoak": ["abiaburu", "hastapen", "hasiera"]},
  {"id": "2-3", "hitza": "abizen", "sinonimoak": ["deitura"]},
  {"id": "2-4", "hitza": "aburu", "sinonimoak": ["uste", "iritzi", "irudiko"]},
  {"id": "2-5", "hitza": "adabaki", "sinonimoak": ["txaplat", "txatalak", "petatxuak"]},
  {"id": "2-6", "hitza": "adats", "sinonimoak": ["ilaje", "menats", "motots"]},
  {"id": "2-7", "hitza": "adeitsu", "sinonimoak": ["gizabidetsu", "xalo", "atsegin"]},
  {"id": "2-8", "hitza": "adimen", "sinonimoak": ["ulermen", "adimendu", "endelgu"]},
  {"id": "2-9", "hitza": "adindua", "sinonimoak": ["edadetua", "atsotua", "adintsua"]},
  {"id": "2-10", "hitza": "adoretsu", "sinonimoak": ["gartsu", "kementsu", "bipil"]},
  {"id": "2-11", "hitza": "afaloste", "sinonimoak": ["afalondo"]},
  {"id": "2-12", "hitza": "afan", "sinonimoak": ["joran", "lehia", "gogo"]},
  {"id": "2-13", "hitza": "aforo", "sinonimoak": ["edukiera", "leku", "toki"]},
  {"id": "2-14", "hitza": "agergarri", "sinonimoak": ["froga", "erakusgarri", "adierazgarri"]},
  {"id": "2-15", "hitza": "agerkari", "sinonimoak": ["aldizkari"]},
  {"id": "2-16", "hitza": "agerkunde", "sinonimoak": ["agerpen", "agerraldi", "agertze"]},
  {"id": "2-17", "hitza": "agian", "sinonimoak": ["apika", "beharbada", "akaso"]},
  {"id": "2-18", "hitza": "agindu", "sinonimoak": ["prometatu", "hitzeman", "promes egin"]},
  {"id": "2-19", "hitza": "agintari", "sinonimoak": ["buruzagi", "buru", "nagusi"]},
  {"id": "2-20", "hitza": "agiraka", "sinonimoak": ["errieta", "haserre", "ahakar"]},

  /* BLOQUE 2 (21-40) */
  {"id": "2-21", "hitza": "agiri", "sinonimoak": ["idazki", "dokumentu"]},
  {"id": "2-22", "hitza": "agitu", "sinonimoak": ["gertatu", "jazo", "iragan"]},
  {"id": "2-23", "hitza": "agorril", "sinonimoak": ["abuztu", "dagonil"]},
  {"id": "2-24", "hitza": "agorteak", "sinonimoak": ["lehorteak", "sikateak", "agorraldiak"]},
  {"id": "2-25", "hitza": "aguazilak", "sinonimoak": ["udaltzainak", "txinelak"]},
  {"id": "2-26", "hitza": "agudo", "sinonimoak": ["laster", "azkar", "fite"]},
  {"id": "2-27", "hitza": "agur", "sinonimoak": ["diosal", "adio"]},
  {"id": "2-28", "hitza": "agure", "sinonimoak": ["zahar", "adintsu", "aitona"]},
  {"id": "2-29", "hitza": "ahaideak", "sinonimoak": ["senideak", "senitartekoak", "familiakoak"]},
  {"id": "2-30", "hitza": "ahaire", "sinonimoak": ["doinu", "melodia"]},
  {"id": "2-31", "hitza": "ahal den lasterren", "sinonimoak": ["lehenbailehen", "albait arinen", "ahalik eta azkarren"]},
  {"id": "2-32", "hitza": "badaezpadako", "sinonimoak": ["zalantzazko", "duda-mudako", "ezbaiko"]},
  {"id": "2-33", "hitza": "bagak", "sinonimoak": ["uhinak", "olatuak"]},
  {"id": "2-34", "hitza": "bailarik", "sinonimoak": ["haranik", "ibarrik", "sakanik"]},
  {"id": "2-35", "hitza": "baina", "sinonimoak": ["ordea", "hala ere", "alabaina"]},
  {"id": "2-36", "hitza": "bakan", "sinonimoak": ["banaka", "urri", "eskas"]},
  {"id": "2-37", "hitza": "baldarkeria", "sinonimoak": ["dorpekeria", "trakeskeria"]},
  {"id": "2-38", "hitza": "baztertu", "sinonimoak": ["zokoratu", "alboratu", "bazterreratu"]},
  {"id": "2-39", "hitza": "begiluze", "sinonimoak": ["kuxkuxero", "nontzeberri", "ikusmiratzaile"]},
  {"id": "2-40", "hitza": "begirale", "sinonimoak": ["jagole", "zaintzaile", "artatzaile"]},

  /* BLOQUE 3 (41-60) */
  {"id": "2-41", "hitza": "begiramen", "sinonimoak": ["begirune", "errespetu", "adeitasun"]},
  {"id": "2-42", "hitza": "belaunaldi", "sinonimoak": ["gizaldi"]},
  {"id": "2-43", "hitza": "beltzune", "sinonimoak": ["ubeldura", "ubelune", "belztasun"]},
  {"id": "2-44", "hitza": "beratu", "sinonimoak": ["bigundu", "leundu", "guritu"]},
  {"id": "2-45", "hitza": "bertute", "sinonimoak": ["dohain", "prestutasun"]},
  {"id": "2-46", "hitza": "betebeharra", "sinonimoak": ["zeregina", "eginkizuna", "eginbeharra"]},
  {"id": "2-47", "hitza": "beterik", "sinonimoak": ["lepo", "gainezka", "mukuru"]},
  {"id": "2-48", "hitza": "betilun", "sinonimoak": ["triste", "goibel", "hits"]},
  {"id": "2-49", "hitza": "bezatu", "sinonimoak": ["hezi", "mantsotu", "otzandu"]},
  {"id": "2-50", "hitza": "bider", "sinonimoak": ["aldiz"]},
  {"id": "2-51", "hitza": "bidezidor", "sinonimoak": ["bidexka", "xendra", "basabide"]},
  {"id": "2-52", "hitza": "bigun", "sinonimoak": ["leun", "guri", "samur"]},
  {"id": "2-53", "hitza": "bilakaera", "sinonimoak": ["eboluzio", "garapen", "eraldaketa"]},
  {"id": "2-54", "hitza": "bitxilorez", "sinonimoak": ["txibiritaz"]},
  {"id": "2-55", "hitza": "bizibide", "sinonimoak": ["ogibide", "lanbide", "ofizio"]},
  {"id": "2-56", "hitza": "biziki", "sinonimoak": ["arras", "oso", "biziro"]},
  {"id": "2-57", "hitza": "blai-blai", "sinonimoak": ["mela-mela", "busti-busti", "putzu-putzu"]},
  {"id": "2-58", "hitza": "bokarta", "sinonimoak": ["antxoa"]},
  {"id": "2-59", "hitza": "borda", "sinonimoak": ["etxola", "txabola"]},
  {"id": "2-60", "hitza": "bordion", "sinonimoak": ["urdanga", "puta", "emagaldu", "maritzar", "julis"]},

  /* BLOQUE 4 (61-80) */
  {"id": "2-61", "hitza": "borondate", "sinonimoak": ["gogo", "nahi", "desira"]},
  {"id": "2-62", "hitza": "borragoma", "sinonimoak": ["ezabagoma", "goma"]},
  {"id": "2-63", "hitza": "bortizkeria", "sinonimoak": ["indarkeria", "gogorkeria", "bortxakeria"]},
  {"id": "2-64", "hitza": "bozkario", "sinonimoak": ["poz", "alegrantzia", "poztasun"]},
  {"id": "2-65", "hitza": "bultzatzaile", "sinonimoak": ["sustatzaile", "eragile"]},
  {"id": "2-66", "hitza": "burugabe", "sinonimoak": ["txoro", "burtzoro", "zentzugabe"]},
  {"id": "2-67", "hitza": "burugogorra", "sinonimoak": ["setatsua", "egoskorra", "tematia"]},
  {"id": "2-68", "hitza": "burutazio", "sinonimoak": ["ideia", "pentsamendu", "gomuta"]},
  {"id": "2-69", "hitza": "burutu", "sinonimoak": ["gauzatu", "obratu", "mamitu"]},
  {"id": "2-70", "hitza": "buruz buruko", "sinonimoak": ["eskuz eskuko", "banakako", "bakarkako"]},
  {"id": "2-71", "hitza": "buztana", "sinonimoak": ["isatsa"]},
  {"id": "2-72", "hitza": "dailuz", "sinonimoak": ["segaz", "kodainaz"]},
  {"id": "2-73", "hitza": "danbada", "sinonimoak": ["danbatekoa", "burrunba", "harrabotsa"]},
  {"id": "2-74", "hitza": "datu", "sinonimoak": ["argibide", "zehaztapen", "azalpen"]},
  {"id": "2-75", "hitza": "deblauki", "sinonimoak": ["bat-batean", "kolpetik", "supituki"]},
  {"id": "2-76", "hitza": "defendaezinak", "sinonimoak": ["eutsiezinak", "sostengaezinak"]},
  {"id": "2-77", "hitza": "deiadar", "sinonimoak": ["oihu", "aldarri", "garrasi"]},
  {"id": "2-78", "hitza": "deitoragarri", "sinonimoak": ["negargarri", "tamalgarri", "penagarri"]},
  {"id": "2-79", "hitza": "deklarazioa", "sinonimoak": ["adierazpena", "jakinarazpena", "azalpena"]},
  {"id": "2-80", "hitza": "dema", "sinonimoak": ["apustu", "postura"]},

  /* BLOQUE 5 (81-100) */
  {"id": "2-81", "hitza": "dena dela", "sinonimoak": ["nolanahi ere", "edonola ere", "dena den"]},
  {"id": "2-82", "hitza": "denda", "sinonimoak": ["saltoki", "postu", "saltegi"]},
  {"id": "2-83", "hitza": "deportatu", "sinonimoak": ["erbesteratu", "arroztu", "atzerriratu"]},
  {"id": "2-84", "hitza": "derrigorrezko", "sinonimoak": ["ezinbesteko", "nahitaezko", "halabeharrezko"]},
  {"id": "2-85", "hitza": "desberindu", "sinonimoak": ["bereizi", "bereiztu", "ezberdindu"]},
  {"id": "2-86", "hitza": "desenkusa", "sinonimoak": ["aitzakia", "estakururen"]},
  {"id": "2-87", "hitza": "desira", "sinonimoak": ["nahia", "gogoa", "guraria"]},
  {"id": "2-88", "hitza": "deslai", "sinonimoak": ["egiteke", "solte"]},
  {"id": "2-89", "hitza": "destinoa", "sinonimoak": ["patua", "halabeharra", "zoria"]},
  {"id": "2-90", "hitza": "deusik", "sinonimoak": ["ezer(txo)", "tutik", "fitsik"]},
  {"id": "2-91", "hitza": "dezenterekin", "sinonimoak": ["nahikorekin", "askirekin", "askotxorekin"]},
  {"id": "2-92", "hitza": "dibortziatu", "sinonimoak": ["bereizi", "banandu", "bizi-alargundu"]},
  {"id": "2-93", "hitza": "dieta", "sinonimoak": ["jan-neurri", "jan-lege"]},
  {"id": "2-94", "hitza": "diferentzia", "sinonimoak": ["alde", "ezberdintasun", "desberdintasun"]},
  {"id": "2-95", "hitza": "dirukoi", "sinonimoak": ["diruzale", "zeken", "zikoitz"]},
  {"id": "2-96", "hitza": "dirutzekotan", "sinonimoak": ["aberastekotan", "dirutza egitekotan"]},
  {"id": "2-97", "hitza": "diruzalekeria", "sinonimoak": ["zekenkeria", "zikoizkeria"]},
  {"id": "2-98", "hitza": "distantzia", "sinonimoak": ["tarte", "bitarte"]},
  {"id": "2-99", "hitza": "dohakabeki", "sinonimoak": ["zoritzarrez", "tamalez", "maluruski", "ondikoz", "damurik"]},
  {"id": "2-100", "hitza": "doi-doi", "sinonimoak": ["ozta-ozta", "justu-justu"]}
];