import { WordData } from './types';

export const LEVEL_3_PART_3: WordData[] = [
  /* BLOQUE 1 (201-220) */
  {"id": "3-201", "hitza": "ñaka", "sinonimoak": ["txandrio", "engainu", "iruzur"]},
  {"id": "3-202", "hitza": "nakan", "sinonimoak": ["orezta", "orin", "natu"]},
  {"id": "3-203", "hitza": "nakez", "sinonimoak": ["gaitz", "zailki", "kostata"]},
  {"id": "3-204", "hitza": "narrio", "sinonimoak": ["akats", "oker", "hutsegite"]},
  {"id": "3-205", "hitza": "nasaia", "sinonimoak": ["zabala", "lasaia", "arina"]},
  {"id": "3-206", "hitza": "naturan", "sinonimoak": ["izadian"]},
  {"id": "3-207", "hitza": "ñauka", "sinonimoak": ["miauka", "marrakaka", "mauka"]},
  {"id": "3-208", "hitza": "nazkagarria", "sinonimoak": ["higuingarria", "nardagarria"]},
  {"id": "3-209", "hitza": "negargarria", "sinonimoak": ["zoritzar", "ezbehar", "malur"]},
  {"id": "3-210", "hitza": "nerabetasuna", "sinonimoak": ["nerabezaroa", "adoleszentzia"]},
  {"id": "3-211", "hitza": "neroni", "sinonimoak": ["neuri", "niri"]},
  {"id": "3-212", "hitza": "neurriko", "sinonimoak": ["tamainako", "moduko", "dimentsioko"]},
  {"id": "3-213", "hitza": "neurtezina", "sinonimoak": ["neurgaitza", "neurgea"]},
  {"id": "3-214", "hitza": "nihaur", "sinonimoak": ["ni", "neu", "nerau"]},
  {"id": "3-215", "hitza": "niketz", "sinonimoak": ["nire partez", "nire aldetik", "nire izenean"]},
  {"id": "3-216", "hitza": "ñiki-ñaka", "sinonimoak": ["txortan", "larrutan", "txikili-txakala"]},
  {"id": "3-217", "hitza": "ñimiñoaren", "sinonimoak": ["ñarroaren", "txikiaren", "ttipiaren"]},
  {"id": "3-218", "hitza": "ninikatzen", "sinonimoak": ["kimatzen", "muskiltzen", "ernamutntzen"]},
  {"id": "3-219", "hitza": "ninikierarik", "sinonimoak": ["umekeriarik", "haurkeriarik", "seinkeriarik"]},
  {"id": "3-220", "hitza": "ñir-ñir", "sinonimoak": ["dir-dir", "diz-diz"]},

  /* BLOQUE 2 (221-240) */
  {"id": "3-221", "hitza": "nobedaderen", "sinonimoak": ["berriren", "albisteren"]},
  {"id": "3-222", "hitza": "nobela", "sinonimoak": ["eleberri"]},
  {"id": "3-223", "hitza": "noharroinari", "sinonimoak": ["behartsuari", "txiroari", "pobreri"]},
  {"id": "3-224", "hitza": "noiznahi", "sinonimoak": ["edonoiz", "noiznahi den", "noizgura"]},
  {"id": "3-225", "hitza": "noiztik", "sinonimoak": ["noizdanik"]},
  {"id": "3-226", "hitza": "nokuak", "sinonimoak": ["akatsak", "hutsuneak", "gabeziak"]},
  {"id": "3-227", "hitza": "nolakatu", "sinonimoak": ["bihurtu", "bilakatu"]},
  {"id": "3-228", "hitza": "nolakotasuna", "sinonimoak": ["ezaugarria", "tasuna", "dohaina"]},
  {"id": "3-229", "hitza": "nolanahiko", "sinonimoak": ["edonolako", "edozein", "halako"]},
  {"id": "3-230", "hitza": "nongotasuna", "sinonimoak": ["jatorria", "sorlekua", "sorterria"]},
  {"id": "3-231", "hitza": "nonzeberri", "sinonimoak": ["kontaktilu", "autubatzaile", "eleberriti"]},
  {"id": "3-232", "hitza": "norabide", "sinonimoak": ["noranzko", "norako"]},
  {"id": "3-233", "hitza": "norgehiagoka", "sinonimoak": ["partida", "norlehenka", "lehia"]},
  {"id": "3-234", "hitza": "normalean", "sinonimoak": ["oro har", "eskuarki", "orokorrean"]},
  {"id": "3-235", "hitza": "nortasunaz", "sinonimoak": ["izaeraz", "jiteaz", "aiurriaz"]},
  {"id": "3-236", "hitza": "noski", "sinonimoak": ["jakina", "noskiro", "ez horixe"]},
  {"id": "3-237", "hitza": "nozitu", "sinonimoak": ["pairatu", "jasan", "izan"]},
  {"id": "3-238", "hitza": "objektoreek", "sinonimoak": ["eragozleek"]},
  {"id": "3-239", "hitza": "obratzen", "sinonimoak": ["libratzen", "sabelusten", "kaka egiten"]},
  {"id": "3-240", "hitza": "odolatuz", "sinonimoak": ["ubelduz", "ubelduraz", "beltzunez"]},

  /* BLOQUE 3 (241-260) */
  {"id": "3-241", "hitza": "odolberoarekin", "sinonimoak": ["haserrekorrarekin", "suminkorrarekin", "suharrarekin"]},
  {"id": "3-242", "hitza": "odolkiak", "sinonimoak": ["odolosteak", "tripotak", "tripotxak"]},
  {"id": "3-243", "hitza": "ofizioz", "sinonimoak": ["lanbidez", "ogibidez", "bizibidez"]},
  {"id": "3-244", "hitza": "ogasundun", "sinonimoak": ["aberats", "ondasundun", "ukandun"]},
  {"id": "3-245", "hitza": "ohaide", "sinonimoak": ["ohelagun", "amorante", "maitale"]},
  {"id": "3-246", "hitza": "ohargarri", "sinonimoak": ["nabarmenki", "nabariki", "argiro"]},
  {"id": "3-247", "hitza": "oharkabekeria", "sinonimoak": ["axolagabekeria", "arduragabekeria", "zabarkeria"]},
  {"id": "3-248", "hitza": "oharpenei", "sinonimoak": ["oharrei", "gaztiguei", "oharkizunei"]},
  {"id": "3-249", "hitza": "ohilduta", "sinonimoak": ["uxatuta", "aienatuta", "izututa"]},
  {"id": "3-250", "hitza": "ohinak", "sinonimoak": ["lapurrak", "ebasleak"]},
  {"id": "3-251", "hitza": "ohitura", "sinonimoak": ["usadio", "aztura", "ekandu"]},
  {"id": "3-252", "hitza": "oiesa", "sinonimoak": ["baldarra", "trauskila", "zakarra"]},
  {"id": "3-253", "hitza": "oiherrra", "sinonimoak": ["bihurria", "okerra", "makurra"]},
  {"id": "3-254", "hitza": "oihuka", "sinonimoak": ["garrasika", "deiadarka", "txilioka"]},
  {"id": "3-255", "hitza": "oilotu", "sinonimoak": ["koldartu", "kikildu", "uzkurtu"]},
  {"id": "3-256", "hitza": "oinarria", "sinonimoak": ["funttsa", "harroina", "abiaburua"]},
  {"id": "3-257", "hitza": "oinatz", "sinonimoak": ["aztarna", "zantzu", "arrasto"]},
  {"id": "3-258", "hitza": "oinatzargi", "sinonimoak": ["tximistargi", "tximista", "oinatzarri"]},
  {"id": "3-259", "hitza": "oinazegarria", "sinonimoak": ["mingarria", "samingarria", "atsekabegarria"]},
  {"id": "3-260", "hitza": "oinordekoa", "sinonimoak": ["jabegaia", "jaraunslea"]},

  /* BLOQUE 4 (261-280) */
  {"id": "3-261", "hitza": "oinutsik", "sinonimoak": ["ortozik", "hanka hutsik", "zankuts"]},
  {"id": "3-262", "hitza": "okaztagarria", "sinonimoak": ["kirasduna", "nazkagarria", "higuingarria"]},
  {"id": "3-263", "hitza": "okela", "sinonimoak": ["haragi", "haragiki", "txitxi"]},
  {"id": "3-264", "hitza": "oker", "sinonimoak": ["erratuta", "tronpatuta", "alferrik"]},
  {"id": "3-265", "hitza": "okerragotu", "sinonimoak": ["areagotu", "larriagotu", "gaizkiagotu"]},
  {"id": "3-266", "hitza": "olagarroa", "sinonimoak": ["eskuluzea"]},
  {"id": "3-267", "hitza": "oldarkorra", "sinonimoak": ["grinatsua", "gartsua", "suharra"]},
  {"id": "3-268", "hitza": "oldozketa", "sinonimoak": ["gogoeta", "hausnarketa", "pentsaketa"]},
  {"id": "3-269", "hitza": "olerkintzarekin", "sinonimoak": ["poemagintzarekin", "poesiagintzarekin"]},
  {"id": "3-270", "hitza": "omenaldia", "sinonimoak": ["gorazarrea"]},
  {"id": "3-271", "hitza": "onartu", "sinonimoak": ["onetsi", "aitortu", "baietsi"]},
  {"id": "3-272", "hitza": "onbeharrak", "sinonimoak": ["pobreziak", "miseriak", "txirotasunak"]},
  {"id": "3-273", "hitza": "onbera", "sinonimoak": ["onegia", "on hutsa", "bihotzbera"]},
  {"id": "3-274", "hitza": "ondarea", "sinonimoak": ["oinordea", "ondoregoa", "jaraunspena"]},
  {"id": "3-275", "hitza": "ondikoz", "sinonimoak": ["tamalez", "zoritxarrez", "maluruski"]},
  {"id": "3-276", "hitza": "ondoko", "sinonimoak": ["alboko", "aldameneko", "pareko"]},
  {"id": "3-277", "hitza": "ondu", "sinonimoak": ["hobetu", "hobekitu", "oneratu"]},
  {"id": "3-278", "hitza": "oniritzia", "sinonimoak": ["onespena", "onarpena", "baimena"]},
  {"id": "3-279", "hitza": "ontsa", "sinonimoak": ["ido", "ongi", "ederki"]},
  {"id": "3-280", "hitza": "onturre", "sinonimoak": ["onura", "probetxu", "etekin"]},

  /* BLOQUE 5 (281-300) */
  {"id": "3-281", "hitza": "oparotasun", "sinonimoak": ["ugaritasun", "joritasun", "narotasun"]},
  {"id": "3-282", "hitza": "oratu", "sinonimoak": ["ekin", "lotu", "eman"]},
  {"id": "3-283", "hitza": "ordaindu", "sinonimoak": ["jasan", "pairatu", "sufritu"]},
  {"id": "3-284", "hitza": "ordea", "sinonimoak": ["ostera", "aldiz", "berriz"]},
  {"id": "3-285", "hitza": "orobat", "sinonimoak": ["halaber", "era berean"]},
  {"id": "3-286", "hitza": "orobat", "sinonimoak": ["halaber", "era berean"]},
  {"id": "3-287", "hitza": "oroiren", "sinonimoak": ["oroitzapen", "gogorapen", "gomuta"]},
  {"id": "3-288", "hitza": "oroiren", "sinonimoak": ["oroitzapen", "gogorapen", "gomuta"]},
  {"id": "3-289", "hitza": "orraztua", "sinonimoak": ["orrazketa", "berrikustea", "gainbegiratua"]},
  {"id": "3-290", "hitza": "orraztua", "sinonimoak": ["orrazketa", "berrikustea", "gainbegiratua"]},
  {"id": "3-291", "hitza": "osoro", "sinonimoak": ["osorik", "guztiz", "goraino"]},
  {"id": "3-292", "hitza": "osoro", "sinonimoak": ["osorik", "guztiz", "goraino"]},
  {"id": "3-293", "hitza": "ospetsua", "sinonimoak": ["entzutetsua", "sonatua", "aipatua"]},
  {"id": "3-294", "hitza": "ospetsua", "sinonimoak": ["entzutetsua", "sonatua", "aipatua"]},
  {"id": "3-295", "hitza": "ospitale", "sinonimoak": ["erietxe", "eritegi"]},
  {"id": "3-296", "hitza": "ospitale", "sinonimoak": ["erietxe", "eritegi"]},
  {"id": "3-297", "hitza": "ostiralean", "sinonimoak": ["barikuan", "ortziralean"]},
  {"id": "3-298", "hitza": "ostiralean", "sinonimoak": ["barikuan", "ortziralean"]},
  {"id": "3-299", "hitza": "otoi", "sinonimoak": ["mesedez", "arren", "faborez"]},
  {"id": "3-300", "hitza": "otoi", "sinonimoak": ["mesedez", "arren", "faborez"]}
];