import { WordData } from './types';

export const LEVEL_2_PART_2: WordData[] = [
  /* BLOQUE 1 (101-120) */
  {"id": "2-101", "hitza": "doilortu", "sinonimoak": ["zitaldu", "zakartu", "petraldu"]},
  {"id": "2-102", "hitza": "donge", "sinonimoak": ["txar", "gaizto", "maltzur"]},
  {"id": "2-103", "hitza": "dorpe", "sinonimoak": ["trakets", "baldar", "baldres"]},
  {"id": "2-104", "hitza": "dotore", "sinonimoak": ["apain", "lirain", "txairo"]},
  {"id": "2-105", "hitza": "dragoiak", "sinonimoak": ["herensugeak"]},
  {"id": "2-106", "hitza": "drolekeriatan", "sinonimoak": ["txantxatan", "bromatan", "olgetatan"]},
  {"id": "2-107", "hitza": "dudarik", "sinonimoak": ["zalantzarik", "ezbairik"]},
  {"id": "2-108", "hitza": "dunbots", "sinonimoak": ["zarata", "zalaparta", "azantz"]},
  {"id": "2-109", "hitza": "dungulu", "sinonimoak": ["morokil", "ahi", "artahi"]},
  {"id": "2-110", "hitza": "durduzadura", "sinonimoak": ["nahasmendu", "nahaste", "laborri"]},
  {"id": "2-111", "hitza": "dutxulua", "sinonimoak": ["txorrota", "txotxa", "zipotza"]},
  {"id": "2-112", "hitza": "ebakera", "sinonimoak": ["ahoskera", "ahoskatze", "ahoskuntza"]},
  {"id": "2-113", "hitza": "ebakuntza", "sinonimoak": ["ebaketa", "operazio"]},
  {"id": "2-114", "hitza": "ebatsi", "sinonimoak": ["lapurtu", "ostu"]},
  {"id": "2-115", "hitza": "ebazpena", "sinonimoak": ["erabakia", "burubidea", "xedapena"]},
  {"id": "2-116", "hitza": "edagale", "sinonimoak": ["egarri", "egarbera", "egartsu"]},
  {"id": "2-117", "hitza": "edendu", "sinonimoak": ["pozoitu", "kutsatu"]},
  {"id": "2-118", "hitza": "ederki", "sinonimoak": ["ederto", "bapo", "primeran"]},
  {"id": "2-119", "hitza": "ederretsi", "sinonimoak": ["preziatu", "balioetsi", "estimatu"]},
  {"id": "2-120", "hitza": "edertu", "sinonimoak": ["liraindu", "zirastu", "ederreztatu"]},

  /* BLOQUE 2 (121-140) */
  {"id": "2-121", "hitza": "edonor", "sinonimoak": ["nornahi", "edozein", "zeinahi"]},
  {"id": "2-122", "hitza": "edukazio", "sinonimoak": ["heziketa", "gizabide", "heziera"]},
  {"id": "2-123", "hitza": "egia-egiatan", "sinonimoak": ["bene-benetan", "alajaina", "alafede"]},
  {"id": "2-124", "hitza": "egiaztagiri", "sinonimoak": ["ziurtagiri", "frogagiri", "zuribide"]},
  {"id": "2-125", "hitza": "egikaritu", "sinonimoak": ["betearazi", "burutu", "obratu"]},
  {"id": "2-126", "hitza": "eginahal", "sinonimoak": ["ahalegin", "entsegua", "esfortzu"]},
  {"id": "2-127", "hitza": "eginkizun", "sinonimoak": ["betebehar", "zeregin", "lan"]},
  {"id": "2-128", "hitza": "egituratu", "sinonimoak": ["programatu", "eratu", "antolatu"]},
  {"id": "2-129", "hitza": "egoiliar", "sinonimoak": ["bizilagun", "etxetiar", "maizter"]},
  {"id": "2-130", "hitza": "egokiera", "sinonimoak": ["aukera", "parada", "abagune"]},
  {"id": "2-131", "hitza": "egonezin", "sinonimoak": ["urduritasun", "artegatasun", "kezka"]},
  {"id": "2-132", "hitza": "egonkorrik", "sinonimoak": ["iraunkorrik", "finkorik"]},
  {"id": "2-133", "hitza": "egoskorra", "sinonimoak": ["setatia", "burugogorra", "tematsua"]},
  {"id": "2-134", "hitza": "egotetxe", "sinonimoak": ["aterpetxe", "ostatu", "babesleku"]},
  {"id": "2-135", "hitza": "egotzi", "sinonimoak": ["leporatu", "bota", "gaineratu"]},
  {"id": "2-136", "hitza": "egunabar", "sinonimoak": ["egunsenti", "goizalde", "goiztiri"]},
  {"id": "2-137", "hitza": "egundoko", "sinonimoak": ["sekulako", "izugarrizko", "itzelezko"]},
  {"id": "2-138", "hitza": "ehortz", "sinonimoak": ["lurpera", "hobira"]},
  {"id": "2-139", "hitza": "eihera", "sinonimoak": ["errota", "bolu"]},
  {"id": "2-140", "hitza": "eite", "sinonimoak": ["itxura", "irudi", "jite"]},

  /* BLOQUE 3 (141-160) */
  {"id": "2-141", "hitza": "ekain", "sinonimoak": ["bagil", "ereiaro"]},
  {"id": "2-142", "hitza": "ekoizlerik", "sinonimoak": ["sortzailerik", "produzitzailerik", "produktorerik"]},
  {"id": "2-143", "hitza": "ekortu", "sinonimoak": ["erraztatu", "eskobatu", "erratzez garbitu"]},
  {"id": "2-144", "hitza": "ekuru", "sinonimoak": ["lasai", "trankil", "patxadatsu"]},
  {"id": "2-145", "hitza": "elai", "sinonimoak": ["enara"]},
  {"id": "2-146", "hitza": "enbarazu", "sinonimoak": ["traba", "oztopo", "eragozpen"]},
  {"id": "2-147", "hitza": "enparauak", "sinonimoak": ["gainerakoak", "gainontzekoak", "uzkinak"]},
  {"id": "2-148", "hitza": "entzuten", "sinonimoak": ["aditzen"]},
  {"id": "2-149", "hitza": "entzutetsua", "sinonimoak": ["ospetsua", "famatua", "sonatua"]},
  {"id": "2-150", "hitza": "erabaki", "sinonimoak": ["zirt edo zart", "ebatzi", "xedatu"]},
  {"id": "2-151", "hitza": "erabat", "sinonimoak": ["guztiz", "zeharo", "arras"]},
  {"id": "2-152", "hitza": "erabilgarri", "sinonimoak": ["maneiagarri", "erabilerraz", "maneiukor"]},
  {"id": "2-153", "hitza": "eragin", "sinonimoak": ["sorrarazi", "izanarazi", "edukiarazi"]},
  {"id": "2-154", "hitza": "eragotzi", "sinonimoak": ["galarazi", "debekatu", "oztopatu"]},
  {"id": "2-155", "hitza": "erakusleihoz", "sinonimoak": ["erakustokiz"]},
  {"id": "2-156", "hitza": "eranskina", "sinonimoak": ["gehigarria", "osagarria"]},
  {"id": "2-157", "hitza": "erbestean", "sinonimoak": ["deserrian", "atzerrian"]},
  {"id": "2-158", "hitza": "erbinuderik", "sinonimoak": ["ogigaztarik"]},
  {"id": "2-159", "hitza": "erdeinagarriak", "sinonimoak": ["mespretxagarriak", "gaitzesgarriak", "baztergarriak"]},
  {"id": "2-160", "hitza": "erdietsitako", "sinonimoak": ["lortutako", "eskuratutako", "jadetsitako"]},

  /* BLOQUE 4 (161-180) */
  {"id": "2-161", "hitza": "ergela", "sinonimoak": ["leloa", "tentela", "kaikua"]},
  {"id": "2-162", "hitza": "erpin", "sinonimoak": ["tontor", "gailur", "gain"]},
  {"id": "2-163", "hitza": "errieta", "sinonimoak": ["haserre", "agiraka", "ahakar"]},
  {"id": "2-164", "hitza": "errukirik", "sinonimoak": ["gupidarik", "urrikalmendurik", "errukitasunik"]},
  {"id": "2-165", "hitza": "etxekotu", "sinonimoak": ["bertakotu", "lekukotu", "tokikotu"]},
  {"id": "2-166", "hitza": "eutsi", "sinonimoak": ["heldu", "oratu", "lotu"]},
  {"id": "2-167", "hitza": "ezetsi", "sinonimoak": ["ukatu", "baztertu", "errefusatu"]},
  {"id": "2-168", "hitza": "ezinbestez", "sinonimoak": ["halabeharrez", "nahitaez", "derrigorrean"]},
  {"id": "2-169", "hitza": "ezinikusi", "sinonimoak": ["gorroto", "herra", "higuin"]},
  {"id": "2-170", "hitza": "ezizena", "sinonimoak": ["goitizena", "izengoitia", "gaitzizena"]},
  {"id": "2-171", "hitza": "ezustea", "sinonimoak": ["ustekabea"]},
  {"id": "2-172", "hitza": "faborez", "sinonimoak": ["mesedez", "arren", "otoi"]},
  {"id": "2-173", "hitza": "faltak", "sinonimoak": ["gabeziak", "ezak", "eskasiak"]},
  {"id": "2-174", "hitza": "fama", "sinonimoak": ["ospe", "entzute", "omen"]},
  {"id": "2-175", "hitza": "familiarteko", "sinonimoak": ["senide", "senitarteko", "ahaide"]},
  {"id": "2-176", "hitza": "fededunagoak", "sinonimoak": ["sinestedunagoak", "sinestunagoak", "sinesleagoak"]},
  {"id": "2-177", "hitza": "fereka", "sinonimoak": ["laztan", "txera"]},
  {"id": "2-178", "hitza": "festak", "sinonimoak": ["jaiak", "bestak"]},
  {"id": "2-179", "hitza": "fidela", "sinonimoak": ["leiala", "zintzoa", "ona"]},
  {"id": "2-180", "hitza": "fildak", "sinonimoak": ["zarpailak", "piltzarrak", "zarpak"]},

  /* BLOQUE 5 (181-200) */
  {"id": "2-181", "hitza": "finagoak", "sinonimoak": ["trebeagoak", "zintzoagoak", "hobeak"]},
  {"id": "2-182", "hitza": "finkatu", "sinonimoak": ["ezarri", "zehaztu", "mugatu"]},
  {"id": "2-183", "hitza": "finkoak", "sinonimoak": ["tinkoak", "irmoak", "zurrunak"]},
  {"id": "2-184", "hitza": "fitsik", "sinonimoak": ["tutik", "deusik", "zipitzik"]},
  {"id": "2-185", "hitza": "flakatu", "sinonimoak": ["argaldu", "mehetu", "lerdendu"]},
  {"id": "2-186", "hitza": "flako", "sinonimoak": ["ahul", "makal", "indarge"]},
  {"id": "2-187", "hitza": "formala", "sinonimoak": ["zintzoa", "zentzuduna", "prestua"]},
  {"id": "2-188", "hitza": "franko", "sinonimoak": ["asko", "ugari", "anitz"]},
  {"id": "2-189", "hitza": "fresko", "sinonimoak": ["hozkirri", "hozgiro", "freskura"]},
  {"id": "2-190", "hitza": "frogatzeko", "sinonimoak": ["egiaztatzeko", "ziurtatzeko", "adierazteko"]},
  {"id": "2-191", "hitza": "funts", "sinonimoak": ["oinarri", "zentzu", "zimendu"]},
  {"id": "2-192", "hitza": "gaberik", "sinonimoak": ["barik", "gabetarik"]},
  {"id": "2-193", "hitza": "Gabonak", "sinonimoak": ["Eguberriak"]},
  {"id": "2-194", "hitza": "gailendu", "sinonimoak": ["nagusitu", "nabarmendu", "gailen gelditu"]},
  {"id": "2-195", "hitza": "gain", "sinonimoak": ["gainera", "lekora", "landa"]},
  {"id": "2-196", "hitza": "gainazal", "sinonimoak": ["azalera", "gainaldea", "hedadura"]},
  {"id": "2-197", "hitza": "gaineratu", "sinonimoak": ["gehitu", "erantsi"]},
  {"id": "2-198", "hitza": "gaitasun", "sinonimoak": ["trebetasun", "iaiotasun", "abilezia"]},
  {"id": "2-199", "hitza": "gaitu", "sinonimoak": ["prestatu", "gertatu", "egokitu"]},
  {"id": "2-200", "hitza": "gaitza", "sinonimoak": ["zaila", "nekeza"]}
];