import { WordData } from './types';

export const LEVEL_4_PART_3: WordData[] = [
  {"id": "4-201", "hitza": "tarrapatan", "sinonimoak": ["arrapaladan", "zistuan", "itsumustuan"]},
  {"id": "4-202", "hitza": "taxurik", "sinonimoak": ["mainarik", "trebeziarik", "arterik"]},
  {"id": "4-203", "hitza": "taxutu", "sinonimoak": ["prestatu", "antolatu", "eratu"]},
  {"id": "4-204", "hitza": "teiuak", "sinonimoak": ["lizunak", "likitsak", "lohiak"]},
  {"id": "4-205", "hitza": "tekua", "sinonimoak": ["kiratsa", "kerua", "sunda"]},
  {"id": "4-206", "hitza": "tenperaturan", "sinonimoak": ["hobeberoan"]},
  {"id": "4-207", "hitza": "tentagarria", "sinonimoak": ["erakargarria", "zirikagarria", "desiragarria"]},
  {"id": "4-208", "hitza": "tenteldu", "sinonimoak": ["txepeldu", "tontotu", "ergeldu"]},
  {"id": "4-209", "hitza": "tentetzen", "sinonimoak": ["zutitzen", "zutuntzen"]},
  {"id": "4-210", "hitza": "tentutik", "sinonimoak": ["senetik", "onetik"]},
  {"id": "4-211", "hitza": "terrenta", "sinonimoak": ["ohikeria", "errutina", "ohitura"]},
  {"id": "4-212", "hitza": "testiguak", "sinonimoak": ["lekukoak"]},
  {"id": "4-213", "hitza": "testuinguruan", "sinonimoak": ["ingurubarrean", "ingurunean", "egoeran"]},
  {"id": "4-214", "hitza": "tetele-metele", "sinonimoak": ["tontoki", "axolagabeki", "funtsgabeki"]},
  {"id": "4-215", "hitza": "tinkoagoak", "sinonimoak": ["sendoagoak", "irmoagoak", "finkoagoak"]},
  {"id": "4-216", "hitza": "tipilgorriak", "sinonimoak": ["biluziak", "biluzgorriak", "larrugorriak"]},
  {"id": "4-217", "hitza": "tirabira", "sinonimoak": ["liskarra", "eztabaida", "kalapita"]},
  {"id": "4-218", "hitza": "tiragaleak", "sinonimoak": ["nagiak", "sagaiak"]},
  {"id": "4-219", "hitza": "tirriagarria", "sinonimoak": ["desiragarria", "tentagarria", "erakargarria"]},
  {"id": "4-220", "hitza": "tirtirina", "sinonimoak": ["poxpolina", "pertxenta", "mari-apaina"]},
  {"id": "4-221", "hitza": "toildu", "sinonimoak": ["nagitu", "alfertu", "zabartu"]},
  {"id": "4-222", "hitza": "tokoloa", "sinonimoak": ["potoloa", "lodikotea", "papalotea"]},
  {"id": "4-223", "hitza": "tontorrera", "sinonimoak": ["gailurrera", "erpinera", "gora"]},
  {"id": "4-224", "hitza": "tortilla", "sinonimoak": ["arrautzopila"]},
  {"id": "4-225", "hitza": "traba", "sinonimoak": ["oztopo", "enbarazu", "eragozpen"]},
  {"id": "4-226", "hitza": "trankildu", "sinonimoak": ["naretu", "lasaitu", "ibitu"]},
  {"id": "4-227", "hitza": "tranpati", "sinonimoak": ["iruzurti", "amarrutsu", "azpijale"]},
  {"id": "4-228", "hitza": "trapadu", "sinonimoak": ["mozkote", "potolo", "zaparrote"]},
  {"id": "4-229", "hitza": "traturik", "sinonimoak": ["harremanik", "tratabiderik", "erlaziorik"]},
  {"id": "4-230", "hitza": "trebatzeko", "sinonimoak": ["gaitzeko", "hornitzeko", "ikasteko"]},
  {"id": "4-231", "hitza": "trenkatuz", "sinonimoak": ["moztuz", "eragotziz", "oztopatuz"]},
  {"id": "4-232", "hitza": "trimindu", "sinonimoak": ["txikitu", "suntsitu", "birrindu"]},
  {"id": "4-233", "hitza": "triskilatu", "sinonimoak": ["suntsitu", "hondatu", "birrindu"]},
  {"id": "4-234", "hitza": "tronpatu", "sinonimoak": ["erratu", "okertu", "nahastu"]},
  {"id": "4-235", "hitza": "trufaka", "sinonimoak": ["isekaka", "burlaka", "txantxaka"]},
  {"id": "4-236", "hitza": "trukatzen", "sinonimoak": ["ematen", "egiten", "aldatzen"]},
  {"id": "4-237", "hitza": "trumilka", "sinonimoak": ["tropelka", "saldoka", "samaldaka"]},
  {"id": "4-238", "hitza": "tunka", "sinonimoak": ["umore", "aldarte", "gogo"]},
  {"id": "4-239", "hitza": "txainku", "sinonimoak": ["herren", "maingu", "trankin"]},
  {"id": "4-240", "hitza": "txaldantzen", "sinonimoak": ["txepeltzen", "ergeltzen", "lelotzen"]},
  {"id": "4-241", "hitza": "txalogarria", "sinonimoak": ["laudagarria", "goresgarria", "goragarria"]},
  {"id": "4-242", "hitza": "txanbila", "sinonimoak": ["pegarra", "suila", "txantxila"]},
  {"id": "4-243", "hitza": "txarkeria", "sinonimoak": ["gaiztakeria", "bihurrikeria", "deabrukeria"]},
  {"id": "4-244", "hitza": "txarretsi", "sinonimoak": ["gaitzetsi", "ezetsi", "hastandu"]},
  {"id": "4-245", "hitza": "txatxu", "sinonimoak": ["txotxolo", "txepel", "ganorabako"]},
  {"id": "4-246", "hitza": "txepeldu", "sinonimoak": ["kikildu", "beldurtu", "koldartu"]},
  {"id": "4-247", "hitza": "txerrikeria", "sinonimoak": ["zikinkeria", "lohi", "zabor"]},
  {"id": "4-248", "hitza": "txertatu", "sinonimoak": ["eman", "tartekatu", "egokitu"]},
  {"id": "4-249", "hitza": "txikertu", "sinonimoak": ["txiki(ago)tu", "murriztu", "gutxitu"]},
  {"id": "4-250", "hitza": "txikietsi", "sinonimoak": ["mespretxatu", "erdeinatu", "gutxietsi"]},
  {"id": "4-251", "hitza": "tximarro", "sinonimoak": ["txima", "zarpa", "ilaje"]},
  {"id": "4-252", "hitza": "tximista", "sinonimoak": ["oinaztura", "oinaztarri", "oinazkar"]},
  {"id": "4-253", "hitza": "txintxoa", "sinonimoak": ["formala", "ona", "zentzuzkoa"]},
  {"id": "4-254", "hitza": "txiripa", "sinonimoak": ["zorte", "zori", "asturru"]},
  {"id": "4-255", "hitza": "txiroen", "sinonimoak": ["pobreen", "behartsuen", "landerren"]},
  {"id": "4-256", "hitza": "txirriporro", "sinonimoak": ["zalaparta", "harrabots", "zarata"]},
  {"id": "4-257", "hitza": "txirrist", "sinonimoak": ["laprast", "labain", "irrist"]},
  {"id": "4-258", "hitza": "txit", "sinonimoak": ["guztiz", "zeharo", "biziki"]},
  {"id": "4-259", "hitza": "txitean-pitean", "sinonimoak": ["maiz", "sarri", "usu"]},
  {"id": "4-260", "hitza": "txo", "sinonimoak": ["to", "txotxo", "motel"]},
  {"id": "4-261", "hitza": "txoil", "sinonimoak": ["guztiz", "erabat", "arras"]},
  {"id": "4-262", "hitza": "txoratuta", "sinonimoak": ["txora-txora eginda", "liluratuta", "xarmatuta"]},
  {"id": "4-263", "hitza": "txorrotxoak", "sinonimoak": ["txioak", "txinttak", "txiruliruak"]},
  {"id": "4-264", "hitza": "txortan", "sinonimoak": ["larrutan", "ñaka", "txikili-txakala"]},
  {"id": "4-265", "hitza": "txotxina", "sinonimoak": ["kaskarina", "txolina", "txoriburua"]},
  {"id": "4-266", "hitza": "txukuntzea", "sinonimoak": ["egokitzea", "prestatzea", "atontzea"]},
  {"id": "4-267", "hitza": "txundigarriak", "sinonimoak": ["harrigarriak", "espantagarriak", "bitxiak"]},
  {"id": "4-268", "hitza": "txunxturreraino", "sinonimoak": ["tontorreraino", "gailurreraino", "goraino"]},
  {"id": "4-269", "hitza": "ubeldu", "sinonimoak": ["ilundu", "beltztu", "goibeldu"]},
  {"id": "4-270", "hitza": "ubidea", "sinonimoak": ["ibilgua", "ibilbidea", "erretena"]},
  {"id": "4-271", "hitza": "udagoieneko", "sinonimoak": ["udazkeneko"]},
  {"id": "4-272", "hitza": "udaletxea", "sinonimoak": ["herriko etxea", "herri-etxea"]},
  {"id": "4-273", "hitza": "udare", "sinonimoak": ["madari"]},
  {"id": "4-274", "hitza": "ugaldu", "sinonimoak": ["ugaritu", "gehigotu", "areagotu"]},
  {"id": "4-275", "hitza": "ugazaba", "sinonimoak": ["nagusi", "ostalari", "ostaler"]},
  {"id": "4-276", "hitza": "ugerrak", "sinonimoak": ["herdoilak", "oxidoak"]},
  {"id": "4-277", "hitza": "uhanditzen", "sinonimoak": ["harroputzen", "hanpatzen", "harrotzen"]},
  {"id": "4-278", "hitza": "uharak", "sinonimoak": ["uberak", "lorratzak", "arrastoak"]},
  {"id": "4-279", "hitza": "ukazio", "sinonimoak": ["ukapen", "ezezko", "ukamen"]},
  {"id": "4-280", "hitza": "ukuilua", "sinonimoak": ["korta", "abeltegia"]},
  {"id": "4-281", "hitza": "ulerkorragoa", "sinonimoak": ["adikorragoa", "adeitsuagoa", "harkorragoa"]},
  {"id": "4-282", "hitza": "ulituko", "sinonimoak": ["koldartuko", "kikilduko", "uzkurtuko"]},
  {"id": "4-283", "hitza": "uluka", "sinonimoak": ["uhurika", "ainurika"]},
  {"id": "4-284", "hitza": "umeldu", "sinonimoak": ["hezetu", "ezkotu", "busti"]},
  {"id": "4-285", "hitza": "umeteria", "sinonimoak": ["haurreria", "haur-taldea", "haur-jendea"]},
  {"id": "4-286", "hitza": "umilak", "sinonimoak": ["apalak", "xumeak", "xeheak"]},
  {"id": "4-287", "hitza": "umoretsu", "sinonimoak": ["pozik", "alai", "alegera"]},
  {"id": "4-288", "hitza": "umotu", "sinonimoak": ["heldu", "nagusitu", "haginak berdindu"]},
  {"id": "4-289", "hitza": "unagarria", "sinonimoak": ["nekagarria", "aspergarria", "gogaikarria"]},
  {"id": "4-290", "hitza": "upategia", "sinonimoak": ["arandegia", "ardangela", "upeletegia"]},
  {"id": "4-291", "hitza": "uraldiak", "sinonimoak": ["uholdeak", "urpetzeak"]},
  {"id": "4-292", "hitza": "urardotu", "sinonimoak": ["hutsaldu", "desitxuratu", "desnaturalizatu"]},
  {"id": "4-293", "hitza": "urburu", "sinonimoak": ["iturburu", "iturbegi", "iturri"]},
  {"id": "4-294", "hitza": "urdailean", "sinonimoak": ["sabelean"]},
  {"id": "4-295", "hitza": "urdekeriarik", "sinonimoak": ["txerrikeriarik", "zikinkeriarik", "zerrikeriarik"]},
  {"id": "4-296", "hitza": "urdindu", "sinonimoak": ["zuritu"]},
  {"id": "4-297", "hitza": "urduritasuna", "sinonimoak": ["artegatasuna", "larritasuna", "egonezina"]},
  {"id": "4-298", "hitza": "uretaratuko", "sinonimoak": ["pulunpatuko", "urperatuko", "murgilduko"]},
  {"id": "4-299", "hitza": "urgazle", "sinonimoak": ["laguntzaile", "kolaboratzaile"]},
  {"id": "4-300", "hitza": "urgoia", "sinonimoak": ["lotsatia", "herabetia", "uzkurra"]}
];