import { WordData } from './types';

export const LEVEL_4_PART_2: WordData[] = [
   {"id": "4-101", "hitza": "sabelandi", "sinonimoak": ["tripontzi", "jatun", "sabelkoi"]},
  {"id": "4-103", "hitza": "sabelgorriak", "sinonimoak": ["basatiak", "ankerrak", "bihotzgabeak"]},
  {"id": "4-105", "hitza": "sagarno", "sinonimoak": ["sagardo"]},
  {"id": "4-107", "hitza": "sagarroia", "sinonimoak": ["trikua", "kirikinoa"]},
  {"id": "4-109", "hitza": "saihesbide", "sinonimoak": ["desbideratze"]},
  {"id": "4-111", "hitza": "saihests", "sinonimoak": ["alderdi", "alde", "puntu"]},
  {"id": "4-113", "hitza": "sailkatu", "sinonimoak": ["ordenatu", "antolatu", "apailatu"]},
  {"id": "4-115", "hitza": "saiokoak", "sinonimoak": ["ahaleginak", "ekinaldiak", "saialdiak"]},
  {"id": "4-117", "hitza": "sakela", "sinonimoak": ["patrika", "poltsiko"]},
  {"id": "4-119", "hitza": "salgai", "sinonimoak": ["salkizun", "salmentan", "saltzen"]},
  {"id": "4-121", "hitza": "saltsa", "sinonimoak": ["nahaspila", "zalaparta", "katramila"]},
  {"id": "4-123", "hitza": "samalda", "sinonimoak": ["mordoa", "andana", "piloa"]},
  {"id": "4-125", "hitza": "samurtzeko", "sinonimoak": ["biguntzeko", "hunkitzeko", "leuntzeko"]},
  {"id": "4-127", "hitza": "sarbidea", "sinonimoak": ["sarrera", "sartzea", "atea"]},
  {"id": "4-129", "hitza": "srealdian", "sinonimoak": ["sarekadan"]},
  {"id": "4-131", "hitza": "saria", "sinonimoak": ["ordainsaria", "donaria", "golardoa"]},
  {"id": "4-133", "hitza": "sarraskirik", "sinonimoak": ["triskantzarik", "txikiziorik", "sakailarik"]},
  {"id": "4-135", "hitza": "sarritan", "sinonimoak": ["askotan", "maiz", "usu"]},
  {"id": "4-137", "hitza": "sasien", "sinonimoak": ["sastraken", "sasitzen", "sastrakadien"]},
  {"id": "4-139", "hitza": "sastakoetako", "sinonimoak": ["labankadetako", "aiztokadetako", "sastadetako"]},
  {"id": "4-141", "hitza": "sastarrez", "sinonimoak": ["zaborrez", "zakarrez", "zaramaz"]},
  {"id": "4-143", "hitza": "segizio", "sinonimoak": ["jarraipen", "segida", "ondorio"]},
  {"id": "4-145", "hitza": "segur aski", "sinonimoak": ["ziur asko", "ziurrenik", "segurutik"]},
  {"id": "4-147", "hitza": "seinale", "sinonimoak": ["adierazgarri", "froga", "erakusgarri"]},
  {"id": "4-149", "hitza": "semebitxia", "sinonimoak": ["seme pontekoa", "seme besoetakoa"]},
  {"id": "4-151", "hitza": "sendagaitzak", "sinonimoak": ["osagaitzak"]},
  {"id": "4-153", "hitza": "sendoro", "sinonimoak": ["tinko", "irmoki", "sendo(ki)"]},
  {"id": "4-155", "hitza": "senekoa", "sinonimoak": ["izaerakoa", "aiurrikoa", "setakoa"]},
  {"id": "4-157", "hitza": "senitartekorik", "sinonimoak": ["seniderik", "familiarrik", "ahaiderik"]},
  {"id": "4-159", "hitza": "senperrenak", "sinonimoak": ["gorriak", "senperrak", "beltzak"]},
  {"id": "4-161", "hitza": "senteriaren", "sinonimoak": ["ongizatearen"]},
  {"id": "4-163", "hitza": "sentiberatasun", "sinonimoak": ["sentikortasun", "minberatasun", "gaitzikortasun"]},
  {"id": "4-165", "hitza": "serioski", "sinonimoak": ["benetan", "egitan", "zinez"]},
  {"id": "4-167", "hitza": "setaturik", "sinonimoak": ["tematurik", "hisiaturik", "gogorturik"]},
  {"id": "4-169", "hitza": "sigi-sagan", "sinonimoak": ["esemeseka", "harat-honatean"]},
  {"id": "4-171", "hitza": "siku", "sinonimoak": ["ziplo", "zerraldo"]},
  {"id": "4-173", "hitza": "simaurra", "sinonimoak": ["ongarri", "gorotza", "satsa"]},
  {"id": "4-175", "hitza": "sineste", "sinonimoak": ["sinesmen", "sineskera", "ideia"]},
  {"id": "4-177", "hitza": "sinkusa", "sinonimoak": ["aitzakia", "estakuru", "desenkusa"]},
  {"id": "4-179", "hitza": "sirats", "sinonimoak": ["atsegin", "plazer", "gustu"]},
  {"id": "4-181", "hitza": "soberako", "sinonimoak": ["gehiegizko", "neurriz gaineko", "demaseko"]},
  {"id": "4-183", "hitza": "soilketa", "sinonimoak": ["mozketa", "ebaketa", "botatzea"]},
  {"id": "4-185", "hitza": "soingainean", "sinonimoak": ["bizkarrean", "lepoan", "sorbaldan"]},
  {"id": "4-186", "hitza": "solastatzen", "sinonimoak": ["mintzatzen", "elekatzen", "mintzo"]},
  {"id": "4-187", "hitza": "soluzioren", "sinonimoak": ["konponbideren", "irtenbideren", "aterabideren"]},
  {"id": "4-188", "hitza": "sorrera", "sinonimoak": ["hastapena", "jatorria", "iturburua"]},
  {"id": "4-189", "hitza": "suertatu", "sinonimoak": ["egokitu", "egon", "izan"]},
  {"id": "4-190", "hitza": "sumatzen", "sinonimoak": ["igartzen", "nabaritzen", "antzematen"]},
  {"id": "4-191", "hitza": "tairik", "sinonimoak": ["etenik", "geldialdirik", "etenaldirik"]},
  {"id": "4-192", "hitza": "taka-taka", "sinonimoak": ["tipi-tapa", "pitinka-pitinka", "gutxika-gutxika"]},
  {"id": "4-193", "hitza": "talapastatu", "sinonimoak": ["nahasi", "nahastatu", "irauli"]},
  {"id": "4-194", "hitza": "taldekatuko", "sinonimoak": ["multzokatuko", "elkartuko", "batuko"]},
  {"id": "4-195", "hitza": "talkaren", "sinonimoak": ["kolpearen", "danbatekoaren", "kroskaren"]},
  {"id": "4-196", "hitza": "tamainan", "sinonimoak": ["primeran", "ederto", "bikain"]},
  {"id": "4-197", "hitza": "tamalgarria", "sinonimoak": ["penagarria", "deitoragarria", "damugarria"]},
  {"id": "4-198", "hitza": "tanatu", "sinonimoak": ["jausi", "erori", "galdu"]},
  {"id": "4-199", "hitza": "tankera", "sinonimoak": ["itxura", "eite", "irudi"]},
  {"id": "4-200", "hitza": "tapaki", "sinonimoak": ["burusi", "manta"]}
];