
import { WordData } from './types';

export const LEVEL_3_DATA: WordData[] = [
  /* BLOQUE 1 (1-20) */
  { "id": "3-1", "hitza": "deiadar", "sinonimoak": ["oihu", "aldarri", "garrasi"] },
  { "id": "3-2", "hitza": "deitoragarri", "sinonimoak": ["negargarri", "tamalgarri", "penagarri"] },
  { "id": "3-3", "hitza": "deklarazioa", "sinonimoak": ["adierazpena", "jakinarazpena", "azalpena"] },
  { "id": "3-4", "hitza": "dema", "sinonimoak": ["apustu", "postura"] },
  { "id": "3-5", "hitza": "dena dela", "sinonimoak": ["nolanahi ere", "edonola ere", "dena den"] },
  { "id": "3-6", "hitza": "denda", "sinonimoak": ["saltoki", "postu", "saltegi"] },
  { "id": "3-7", "hitza": "deportatu", "sinonimoak": ["erbesteratu", "arroztu", "atzerriratu"] },
  { "id": "3-8", "hitza": "derrigorrezko", "sinonimoak": ["ezinbesteko", "nahitaezko", "halabeharrezko"] },
  { "id": "3-9", "hitza": "desberindu", "sinonimoak": ["bereizi", "bereiztu", "ezberdindu"] },
  { "id": "3-10", "hitza": "desenkusa", "sinonimoak": ["aitzakia", "estakururen"] },
  { "id": "3-11", "hitza": "desira", "sinonimoak": ["nahia", "gogoa", "guraria"] },
  { "id": "3-12", "hitza": "deslai", "sinonimoak": ["egiteke", "solte"] },
  { "id": "3-13", "hitza": "destinoa", "sinonimoak": ["patua", "halabeharra", "zoria"] },
  { "id": "3-14", "hitza": "deusik", "sinonimoak": ["ezer(txo)", "tutik", "fitsik"] },
  { "id": "3-15", "hitza": "dezenterekin", "sinonimoak": ["nahikorekin", "askirekin", "askotxorekin"] },
  { "id": "3-16", "hitza": "dibortziatu", "sinonimoak": ["bereizi", "banandu", "bizi-alargundu"] },
  { "id": "3-17", "hitza": "dieta", "sinonimoak": ["jan-neurri", "jan-lege"] },
  { "id": "3-18", "hitza": "diferentzia", "sinonimoak": ["alde", "ezberdintasun", "desberdintasun"] },
  { "id": "3-19", "hitza": "dirukoi", "sinonimoak": ["diruzale", "zeken", "zikoitz"] },
  { "id": "3-20", "hitza": "dirutzekotan", "sinonimoak": ["aberastekotan", "dirutza egitekotan"] },
  { "id": 97, "hitza": "diruzalekeria", "sinonimoak": ["zekenkeria", "zikoizkeria"] },
  { "id": 98, "hitza": "distantzia", "sinonimoak": ["tarte", "bitarte"] },
  { "id": 99, "hitza": "dohakabeki", "sinonimoak": ["zoritzarrez", "tamalez", "maluruski", "ondikoz", "damurik"] },
  { "id": 100, "hitza": "doi-doi", "sinonimoak": ["ozta-ozta", "justu-justu"] },
  { "id": 101, "hitza": "doilortu", "sinonimoak": ["zitaldu", "zakartu", "petraldu"] },
  { "id": 102, "hitza": "donge", "sinonimoak": ["txar", "gaizto", "maltzur"] },
  { "id": 103, "hitza": "dorpe", "sinonimoak": ["trakets", "baldar", "baldres"] },
  { "id": 104, "hitza": "dotore", "sinonimoak": ["apain", "lirain", "txairo"] },
  { "id": 105, "hitza": "dragoiak", "sinonimoak": ["herensugeak"] },
  { "id": 106, "hitza": "drolekeriatan", "sinonimoak": ["txantxatan", "bromatan", "olgetatan"] },
  { "id": 107, "hitza": "dudarik", "sinonimoak": ["zalantzarik", "ezbairik"] },
  { "id": 108, "hitza": "dunbots", "sinonimoak": ["zarata", "zalaparta", "azantz"] },
  { "id": 109, "hitza": "dungulu", "sinonimoak": ["morokil", "ahi", "artahi"] },
  { "id": 110, "hitza": "durduzadura", "sinonimoak": ["nahasmendu", "nahaste", "laborri"] },
  { "id": 111, "hitza": "dutxulua", "sinonimoak": ["txorrota", "txotxa", "zipotza"] },
  { "id": 112, "hitza": "ebakera", "sinonimoak": ["ahoskera", "ahoskatze", "ahoskuntza"] },
  { "id": 113, "hitza": "ebakuntza", "sinonimoak": ["ebaketa", "operazio"] },
  { "id": 114, "hitza": "ebatsi", "sinonimoak": ["lapurtu", "ostu"] },
  { "id": 115, "hitza": "ebazpena", "sinonimoak": ["erabakia", "burubidea", "xedapena"] },
  { "id": 116, "hitza": "edagale", "sinonimoak": ["egarri", "egarbera", "egartsu"] },
  { "id": 117, "hitza": "edendu", "sinonimoak": ["pozoitu", "kutsatu"] },
  { "id": 118, "hitza": "ederki", "sinonimoak": ["ederto", "bapo", "primeran"] },
  { "id": 119, "hitza": "ederretsi", "sinonimoak": ["preziatu", "balioetsi", "estimatu"] },
  { "id": 120, "hitza": "edertu", "sinonimoak": ["liraindu", "zirastu", "ederreztatu"] },
  { "id": 121, "hitza": "edonor", "sinonimoak": ["nornahi", "edozein", "zeinahi"] },
  { "id": 122, "hitza": "edukazio", "sinonimoak": ["heziketa", "gizabide", "heziera"] },
  { "id": 123, "hitza": "egia-egiatan", "sinonimoak": ["bene-benetan", "alajaina", "alafede"] },
  { "id": 124, "hitza": "egiaztagiri", "sinonimoak": ["ziurtagiri", "frogagiri", "zuribide"] },
  { "id": 125, "hitza": "egikaritu", "sinonimoak": ["betearazi", "burutu", "obratu"] },
  { "id": 126, "hitza": "eginahal", "sinonimoak": ["ahalegin", "entsegua", "esfortzu"] },
  { "id": 127, "hitza": "eginkizun", "sinonimoak": ["betebehar", "zeregin", "lan"] },
  { "id": 128, "hitza": "egituratu", "sinonimoak": ["programatu", "eratu", "antolatu"] },
  { "id": 129, "hitza": "egoiliar", "sinonimoak": ["bizilagun", "etxetiar", "maizter"] },
  { "id": 130, "hitza": "egokiera", "sinonimoak": ["aukera", "parada", "abagune"] },
  { "id": 131, "hitza": "egonezin", "sinonimoak": ["urduritasun", "artegatasun", "kezka"] },
  { "id": 132, "hitza": "egonkorrik", "sinonimoak": ["iraunkorrik", "finkorik"] },
  { "id": 133, "hitza": "egoskorra", "sinonimoak": ["setatia", "burugogorra", "tematsua"] },
  { "id": 134, "hitza": "egotetxe", "sinonimoak": ["aterpetxe", "ostatu", "babesleku"] },
  { "id": 135, "hitza": "egotzi", "sinonimoak": ["leporatu", "bota", "gaineratu"] },
  { "id": 136, "hitza": "egunabar", "sinonimoak": ["egunsenti", "goizalde", "goiztiri"] },
  { "id": 137, "hitza": "egundoko", "sinonimoak": ["sekulako", "izugarrizko", "itzelezko"] },
  { "id": 138, "hitza": "ehortz", "sinonimoak": ["lurpera", "hobira"] },
  { "id": 139, "hitza": "eihera", "sinonimoak": ["errota", "bolu"] },
  { "id": 140, "hitza": "eite", "sinonimoak": ["itxura", "irudi", "jite"] },
  { "id": 141, "hitza": "ekain", "sinonimoak": ["bagil", "ereiaro"] },
  { "id": 142, "hitza": "ekoizlerik", "sinonimoak": ["sortzailerik", "produzitzailerik", "produktorerik"] },
  { "id": 143, "hitza": "ekortu", "sinonimoak": ["erraztatu", "eskobatu", "erratzez garbitu"] },
  { "id": 144, "hitza": "ekuru", "sinonimoak": ["lasai", "trankil", "patxadatsu"] },
  { "id": 145, "hitza": "elai", "sinonimoak": ["enara"] },
  { "id": 146, "hitza": "enbarazu", "sinonimoak": ["traba", "oztopo", "eragozpen"] },
  { "id": 147, "hitza": "enparauak", "sinonimoak": ["gainerakoak", "gainontzekoak", "uzkinak"] },
  { "id": 148, "hitza": "entzuten", "sinonimoak": ["aditzen"] },
  { "id": 149, "hitza": "entzutetsua", "sinonimoak": ["ospetsua", "famatua", "sonatua"] },
  { "id": 150, "hitza": "erabaki", "sinonimoak": ["zirt edo zart", "ebatzi", "xedatu"] },
  { "id": 151, "hitza": "erabat", "sinonimoak": ["guztiz", "zeharo", "arras"] },
  { "id": 152, "hitza": "erabilgarri", "sinonimoak": ["maneiagarri", "erabilerraz", "maneiukor"] },
  { "id": 153, "hitza": "eragin", "sinonimoak": ["sorrarazi", "izanarazi", "edukiarazi"] },
  { "id": 154, "hitza": "eragotzi", "sinonimoak": ["galarazi", "debekatu", "oztopatu"] },
  { "id": 155, "hitza": "erakusleihoz", "sinonimoak": ["erakustokiz"] },
  { "id": 156, "hitza": "eranskina", "sinonimoak": ["gehigarria", "osagarria"] },
  { "id": 157, "hitza": "erbestean", "sinonimoak": ["deserrian", "atzerrian"] },
  { "id": 158, "hitza": "erbinuderik", "sinonimoak": ["ogigaztarik"] },
  { "id": 159, "hitza": "erdeinagarriak", "sinonimoak": ["mespretxagarriak", "gaitzesgarriak", "baztergarriak"] },
  { "id": 160, "hitza": "erdietsitako", "sinonimoak": ["lortutako", "eskuratutako", "jadetsitako"] },
  { "id": 161, "hitza": "ergela", "sinonimoak": ["leloa", "tentela", "kaikua"] },
  { "id": 162, "hitza": "erpin", "sinonimoak": ["tontor", "gailur", "gain"] },
  { "id": 163, "hitza": "errieta", "sinonimoak": ["haserre", "agiraka", "ahakar"] },
  { "id": 164, "hitza": "errukirik", "sinonimoak": ["gupidarik", "urrikalmendurik", "errukitasunik"] },
  { "id": 165, "hitza": "etxekotu", "sinonimoak": ["bertakotu", "lekukotu", "tokikotu"] },
  { "id": 166, "hitza": "eutsi", "sinonimoak": ["heldu", "oratu", "lotu"] },
  { "id": 167, "hitza": "ezetsi", "sinonimoak": ["ukatu", "baztertu", "errefusatu"] },
  { "id": 168, "hitza": "ezinbestez", "sinonimoak": ["halabeharrez", "nahitaez", "derrigorrean"] },
  { "id": 169, "hitza": "ezinikusi", "sinonimoak": ["gorroto", "herra", "higuin"] },
  { "id": 170, "hitza": "ezizena", "sinonimoak": ["goitizena", "izengoitia", "gaitzizena"] },
  { "id": 171, "hitza": "ezustea", "sinonimoak": ["ustekabea"] },
  { "id": 172, "hitza": "faborez", "sinonimoak": ["mesedez", "arren", "otoi"] },
  { "id": 173, "hitza": "faltak", "sinonimoak": ["gabeziak", "ezak", "eskasiak"] },
  { "id": 174, "hitza": "fama", "sinonimoak": ["ospe", "entzute", "omen"] },
  { "id": 175, "hitza": "familiarteko", "sinonimoak": ["senide", "senitarteko", "ahaide"] },
  { "id": 176, "hitza": "fededunagoak", "sinonimoak": ["sinestedunagoak", "sinestunagoak", "sinesleagoak"] },
  { "id": 177, "hitza": "fereka", "sinonimoak": ["laztan", "txera"] },
  { "id": 178, "hitza": "festak", "sinonimoak": ["jaiak", "bestak"] },
  { "id": 179, "hitza": "fidela", "sinonimoak": ["leiala", "zintzoa", "ona"] },
  { "id": 180, "hitza": "fildak", "sinonimoak": ["zarpailak", "piltzarrak", "zarpak"] },
  { "id": 181, "hitza": "finagoak", "sinonimoak": ["trebeagoak", "zintzoagoak", "hobeak"] },
  { "id": 182, "hitza": "finkatu", "sinonimoak": ["ezarri", "zehaztu", "mugatu"] },
  { "id": 183, "hitza": "finkoak", "sinonimoak": ["tinkoak", "irmoak", "zurrunak"] },
  { "id": 184, "hitza": "fitsik", "sinonimoak": ["tutik", "deusik", "zipitzik"] }
];
