
import { WordData } from './types';

export const LEVEL_2_DATA: WordData[] = [
  /* BLOQUE 1 (1-20) */
  { "id": "2-1", "hitza": "abaraska", "sinonimoak": ["orrazea", "abaoa", "eztiorrazea"] },
  { "id": "2-2", "hitza": "abiapuntu", "sinonimoak": ["abiaburu", "hastapen", "hasiera"] },
  { "id": "2-3", "hitza": "abizen", "sinonimoak": ["deitura"] },
  { "id": "2-4", "hitza": "aburuz", "sinonimoak": ["ustez", "iritziz", "irudiko(z)"] },
  { "id": "2-5", "hitza": "adabaki", "sinonimoak": ["txaplat", "txatalak", "petatxuak"] },
  { "id": "2-6", "hitza": "adats", "sinonimoak": ["ilaje", "menats", "motots"] },
  { "id": "2-7", "hitza": "adeitsua", "sinonimoak": ["gizabidetsua", "xaloa", "atsegina"] },
  { "id": "2-8", "hitza": "adimen", "sinonimoak": ["ulermen", "adimendu", "endelgu"] },
  { "id": "2-9", "hitza": "adindua", "sinonimoak": ["edadetua", "atsotua", "adintsua"] },
  { "id": "2-10", "hitza": "adoretsu", "sinonimoak": ["gartsu", "kementsu", "bipil"] },
  { "id": "2-11", "hitza": "afaloste", "sinonimoak": ["afalondo"] },
  { "id": "2-12", "hitza": "afanez", "sinonimoak": ["joranez", "lehiaz", "gogoz"] },
  { "id": "2-13", "hitza": "aforoa", "sinonimoak": ["edukiera", "lekua", "tokia"] },
  { "id": "2-14", "hitza": "agergarririk", "sinonimoak": ["frogarik", "erakusgarririk", "adierazgartik"] },
  { "id": "2-15", "hitza": "agerkari", "sinonimoak": ["aldizkari"] },
  { "id": "2-16", "hitza": "agerkunde", "sinonimoak": ["agerpen", "agerraldi", "agertze"] },
  { "id": "2-17", "hitza": "agian", "sinonimoak": ["apika", "beharbada", "akaso"] },
  { "id": "2-18", "hitza": "agindu", "sinonimoak": ["prometatu", "hitzeman", "promes egin"] },
  { "id": "2-19", "hitza": "agintari", "sinonimoak": ["buruzagi", "buru", "nagusi"] },
  { "id": "2-20", "hitza": "agiraka", "sinonimoak": ["errieta", "haserre", "ahakar"] },
  { "id": "2-21", "hitza": "agiraka", "sinonimoak": ["errieta", "haserre", "ahakar"] },
  { "id": "2-22", "hitza": "agiri", "sinonimoak": ["idazki", "dokumentu"] },
  { "id": "2-23", "hitza": "agitu", "sinonimoak": ["gertatu", "jazo", "iragan"] },
  { "id": "2-24", "hitza": "agorril", "sinonimoak": ["abuztu", "dagonil"] },
  { "id": "2-25", "hitza": "agorteak", "sinonimoak": ["lehorteak", "sikateak", "agorraldiak"] },
  { "id": "2-26", "hitza": "aguazilak", "sinonimoak": ["udaltzainak", "txinelak"] },
  { "id": "2-27", "hitza": "agudo", "sinonimoak": ["laster", "azkar", "fite"] },
  { "id": "2-28", "hitza": "agur", "sinonimoak": ["diosal", "adio"] },
  { "id": "2-29", "hitza": "agure", "sinonimoak": ["zahar", "adintsu", "aitona"] },
  { "id": "2-30", "hitza": "ahaideak", "sinonimoak": ["senideak", "senitartekoak", "familiakoak"] },
  { "id": "2-31", "hitza": "ahaire", "sinonimoak": ["doinu", "melodia"] },
  { "id": "2-32", "hitza": "ahal den lasterren", "sinonimoak": ["lehenbailehen", "albait arinen", "ahalik eta azkarren"] },
  { "id": "2-33", "hitza": "badaezpadako", "sinonimoak": ["zalantzazko", "duda-mudako", "ezbaiko"] },
  { "id": "2-34", "hitza": "bagak", "sinonimoak": ["uhinak", "olatuak"] },
  { "id": "2-35", "hitza": "bailarik", "sinonimoak": ["haranik", "ibarrik", "sakanik"] },
  { "id": "2-36", "hitza": "baina", "sinonimoak": ["ordea", "hala ere", "alabaina"] },
  { "id": "2-37", "hitza": "bakan", "sinonimoak": ["banaka", "urri", "eskas"] },
  { "id": "2-38", "hitza": "baldarkeria", "sinonimoak": ["dorpekeria", "trakeskeria"] },
  { "id": "2-39", "hitza": "baztertu", "sinonimoak": ["zokoratu", "alboratu", "bazterreratu"] },
  { "id": "2-40", "hitza": "begiluze", "sinonimoak": ["kuxkuxero", "nontzeberri", "ikusmiratzaile"] },
  { "id": "2-41", "hitza": "begirale", "sinonimoak": ["jagole", "zaintzaile", "artatzaile"] },
  { "id": "2-42", "hitza": "begiramen", "sinonimoak": ["begirune", "errespetu", "adeitasun"] },
  { "id": "2-43", "hitza": "belaunaldi", "sinonimoak": ["gizaldi"] },
  { "id": "2-44", "hitza": "beltzune", "sinonimoak": ["ubeldura", "ubelune", "belztasun"] },
  { "id": "2-45", "hitza": "beratu", "sinonimoak": ["bigundu", "leundu", "guritu"] },
  { "id": "2-46", "hitza": "bertute", "sinonimoak": ["dohain", "prestutasun"] },
  { "id": "2-47", "hitza": "betebeharra", "sinonimoak": ["zeregina", "eginkizuna", "eginbeharra"] },
  { "id": "2-48", "hitza": "beterik", "sinonimoak": ["lepo", "gainezka", "mukuru"] },
  { "id": "2-49", "hitza": "betilun", "sinonimoak": ["triste", "goibel", "hits"] },
  { "id": "2-50", "hitza": "bezatu", "sinonimoak": ["hezi", "mantsotu", "otzandu"] },
  { "id": "2-51", "hitza": "bider", "sinonimoak": ["aldiz"] },
  { "id": "2-52", "hitza": "bidezidor", "sinonimoak": ["bidexka", "xendra", "basabide"] },
  { "id": "2-53", "hitza": "bigun", "sinonimoak": ["leun", "guri", "samur"] },
  { "id": "2-54", "hitza": "bilakaera", "sinonimoak": ["eboluzio", "garapen", "eraldaketa"] },
  { "id": "2-55", "hitza": "bitxilorez", "sinonimoak": ["txibiritaz"] },
  { "id": "2-56", "hitza": "bizibide", "sinonimoak": ["ogibide", "lanbide", "ofizio"] },
  { "id": "2-57", "hitza": "biziki", "sinonimoak": ["arras", "oso", "biziro"] },
  { "id": "2-58", "hitza": "blai-blai", "sinonimoak": ["mela-mela", "busti-busti", "putzu-putzu"] },
  { "id": "2-59", "hitza": "bokarta", "sinonimoak": ["antxoa"] },
  { "id": "2-60", "hitza": "borda", "sinonimoak": ["etxola", "txabola"] },
  { "id": "2-61", "hitza": "bordion", "sinonimoak": ["urdanga", "puta", "emagaldu", "maritzar", "julis"] },
  { "id": "2-62", "hitza": "borondate", "sinonimoak": ["gogo", "nahi", "desira"] },
  { "id": "2-63", "hitza": "borragoma", "sinonimoak": ["ezabagoma", "goma"] },
  { "id": "2-64", "hitza": "bortizkeria", "sinonimoak": ["indarkeria", "gogorkeria", "bortxakeria"] },
  { "id": "2-65", "hitza": "bozkario", "sinonimoak": ["poz", "alegrantzia", "poztasun"] },
  { "id": "2-66", "hitza": "bultzatzaile", "sinonimoak": ["sustatzaile", "eragile"] },
  { "id": "2-67", "hitza": "burugabe", "sinonimoak": ["txoro", "burtzoro", "zentzugabe"] },
  { "id": "2-68", "hitza": "burugogorra", "sinonimoak": ["setatsua", "egoskorra", "tematia"] },
  { "id": "2-69", "hitza": "burutazio", "sinonimoak": ["ideia", "pentsamendu", "gomuta"] },
  { "id": "2-70", "hitza": "burutu", "sinonimoak": ["gauzatu", "obratu", "mamitu"] },
  { "id": "2-71", "hitza": "buruz buruko", "sinonimoak": ["eskuz eskuko", "banakako", "bakarkako"] },
  { "id": "2-72", "hitza": "buztana", "sinonimoak": ["isatsa"] },
  { "id": "2-73", "hitza": "dailuz", "sinonimoak": ["segaz", "kodainaz"] },
  { "id": "2-74", "hitza": "danbada", "sinonimoak": ["danbatekoa", "burrunba", "harrabotsa"] },
  { "id": "2-75", "hitza": "datu", "sinonimoak": ["argibide", "zehaztapen", "azalpen"] },
  { "id": "2-76", "hitza": "deblauki", "sinonimoak": ["bat-batean", "kolpetik", "supituki"] },
  { "id": "2-77", "hitza": "defendaezinak", "sinonimoak": ["eutsiezinak", "sostengaezinak"] }
];
