import { WordData } from './types';

export const LEVEL_3_PART_2: WordData[] = [
  /* BLOQUE 1 (101-120) */
  {"id": "3-101", "hitza": "koadro", "sinonimoak": ["margolan", "pintura", "artelan"]},
  {"id": "3-102", "hitza": "koipetsu", "sinonimoak": ["koipeztu", "ugerdo", "krakatsu"]},
  {"id": "3-103", "hitza": "kokorroa", "sinonimoak": ["zakarra", "oiesa", "kaskarroa"]},
  {"id": "3-104", "hitza": "kokospe", "sinonimoak": ["girgilo"]},
  {"id": "3-105", "hitza": "komuna", "sinonimoak": ["ohikoa", "arrunta", "agizkoa"]},
  {"id": "3-106", "hitza": "koskortzen", "sinonimoak": ["hazten", "handitzen", "tarrotzen"]},
  {"id": "3-107", "hitza": "kraskaturik", "sinonimoak": ["pitzaturik", "arrakalaturik", "arraildurik"]},
  {"id": "3-108", "hitza": "kukutzea", "sinonimoak": ["estaltzea", "ezkutatzea", "ostentzea"]},
  {"id": "3-109", "hitza": "kukuxean", "sinonimoak": ["zokomiran", "ikusmiran", "usainka"]},
  {"id": "3-110", "hitza": "kutsadura", "sinonimoak": ["poluzioa"]},
  {"id": "3-111", "hitza": "kutsua", "sinonimoak": ["ukitua", "eragina", "azentua"]},
  {"id": "3-112", "hitza": "labainkorra", "sinonimoak": ["irristakorra", "lerrakorra", "limurkorra"]},
  {"id": "3-113", "hitza": "laborariak", "sinonimoak": ["nekazariak", "baserritarrak"]},
  {"id": "3-114", "hitza": "laborria", "sinonimoak": ["ikara", "izua", "beldurra"]},
  {"id": "3-115", "hitza": "laga", "sinonimoak": ["utzi", "mailegatu"]},
  {"id": "3-116", "hitza": "lagungarri", "sinonimoak": ["onuragarri", "mesedegarri", "probetxugarri"]},
  {"id": "3-117", "hitza": "laguntzaileek", "sinonimoak": ["azafatek", "harreragileek"]},
  {"id": "3-118", "hitza": "lainotu", "sinonimoak": ["hodeitu", "goibeldu", "ilundu"]},
  {"id": "3-119", "hitza": "laket", "sinonimoak": ["atsegin", "gogoko", "gustuko"]},
  {"id": "3-120", "hitza": "lanabes", "sinonimoak": ["tresna", "erreminta", "langai"]},

  /* BLOQUE 2 (121-140) */
  {"id": "3-121", "hitza": "lanaldi", "sinonimoak": ["lansaio", "lanegun", "jardunaldi"]},
  {"id": "3-122", "hitza": "landerra", "sinonimoak": ["txiroa", "behartsua", "erromesa"]},
  {"id": "3-123", "hitza": "landua", "sinonimoak": ["jasoa", "zaindua", "laboratua"]},
  {"id": "3-124", "hitza": "lanpasean", "sinonimoak": ["zerrian"]},
  {"id": "3-125", "hitza": "latza", "sinonimoak": ["gogorra", "bortitza", "zaila"]},
  {"id": "3-126", "hitza": "laudorioa", "sinonimoak": ["goraipamena", "gorespena", "handiespena"]},
  {"id": "3-127", "hitza": "lausenguak", "sinonimoak": ["losintxak", "koipekeriak", "balakuak"]},
  {"id": "3-128", "hitza": "laztanak", "sinonimoak": ["ferekak", "txerak"]},
  {"id": "3-129", "hitza": "legetxe", "sinonimoak": ["legez", "bezala", "adina"]},
  {"id": "3-130", "hitza": "lehenengoa", "sinonimoak": ["lehenbizikoa", "aurrenekoa", "estreinakoa"]},
  {"id": "3-131", "hitza": "lehengo", "sinonimoak": ["aurreko", "behin"]},
  {"id": "3-132", "hitza": "lehia", "sinonimoak": ["borroka", "norgehiagoka", "konkurrentzia"]},
  {"id": "3-133", "hitza": "leize", "sinonimoak": ["alde", "desberdintasun", "amildegi"]},
  {"id": "3-134", "hitza": "lekukotuz", "sinonimoak": ["bertakotuz", "tokikotuz", "sustraituz"]},
  {"id": "3-135", "hitza": "leporaino", "sinonimoak": ["goraino", "beterik", "gainezka"]},
  {"id": "3-136", "hitza": "lerdea", "sinonimoak": ["adurra"]},
  {"id": "3-137", "hitza": "lerdendu", "sinonimoak": ["liraindu", "zardaitu", "edertu"]},
  {"id": "3-138", "hitza": "leundu", "sinonimoak": ["bigundu", "baretu", "eztitu"]},
  {"id": "3-139", "hitza": "libro", "sinonimoak": ["aske", "libre", "nahierara"]},
  {"id": "3-140", "hitza": "ligain", "sinonimoak": ["gartxu", "jangartxu", "urri-jale"]},

  /* BLOQUE 3 (141-160) */
  {"id": "3-141", "hitza": "likitsa", "sinonimoak": ["zikina", "lizuna", "lohia"]},
  {"id": "3-142", "hitza": "lili", "sinonimoak": ["lore"]},
  {"id": "3-143", "hitza": "liluragarria", "sinonimoak": ["xarmagarria", "zoragarria", "itsugarria"]},
  {"id": "3-144", "hitza": "lipartxo", "sinonimoak": ["unetxo", "istant", "aldiune"]},
  {"id": "3-145", "hitza": "liskarrean", "sinonimoak": ["iskanbilan", "haserrean", "ika-mika"]},
  {"id": "3-146", "hitza": "lixiba", "sinonimoak": ["bokata", "gobada"]},
  {"id": "3-147", "hitza": "lodrota", "sinonimoak": ["lodia", "gizena", "potoloa"]},
  {"id": "3-148", "hitza": "lokarriak", "sinonimoak": ["axubetak", "estekailuak"]},
  {"id": "3-149", "hitza": "loriagarri", "sinonimoak": ["zoragarri", "liluragarria", "txundigarria"]},
  {"id": "3-150", "hitza": "lorratzek", "sinonimoak": ["aztarnek", "oinatzek", "herexek"]},
  {"id": "3-151", "hitza": "lumatu", "sinonimoak": ["bipildu", "ziplatu"]},
  {"id": "3-152", "hitza": "luzetsi", "sinonimoak": ["berantetsi", "kezkatu", "larritu"]},
  {"id": "3-153", "hitza": "magalean", "sinonimoak": ["altzoan", "galtzarrean", "kolkoan"]},
  {"id": "3-154", "hitza": "mahaikide", "sinonimoak": ["bazkaltiar", "bazkalkide", "jankide"]},
  {"id": "3-155", "hitza": "mainontzia", "sinonimoak": ["mainatia", "negartia", "negarrotza"]},
  {"id": "3-156", "hitza": "maisutasun", "sinonimoak": ["trebetasun", "abilezia", "maina"]},
  {"id": "3-157", "hitza": "maitagarria", "sinonimoak": ["zoragarria", "liluragarria", "xarmagarria"]},
  {"id": "3-158", "hitza": "maitale", "sinonimoak": ["amorante", "ohaide", "ohelagun"]},
  {"id": "3-159", "hitza": "maiztasun", "sinonimoak": ["sarritasun", "ohikotasun", "jarraitutasun"]},
  {"id": "3-160", "hitza": "maizterrarekin", "sinonimoak": ["errentariarekin", "akuradunarekin", "etxetiarrarekin"]},

  /* BLOQUE 4 (161-180) */
  {"id": "3-161", "hitza": "makurra", "sinonimoak": ["dongea", "zitalal", "gaiztoa"]},
  {"id": "3-162", "hitza": "marmarka", "sinonimoak": ["xuxurlaka", "murrmurioka", "txutxu-mutxuka"]},
  {"id": "3-163", "hitza": "maskal", "sinonimoak": ["makal", "ahul", "pattal"]},
  {"id": "3-164", "hitza": "meatsa", "sinonimoak": ["argala", "mehea", "makarra"]},
  {"id": "3-165", "hitza": "meharretan", "sinonimoak": ["estuetan", "hertsietan", "itxietan"]},
  {"id": "3-166", "hitza": "mehatxua", "sinonimoak": ["zemaia", "dixidua"]},
  {"id": "3-167", "hitza": "melatuta", "sinonimoak": ["bustita", "blaituta"]},
  {"id": "3-168", "hitza": "mendratu", "sinonimoak": ["gutxitu", "urritu", "eskastu"]},
  {"id": "3-169", "hitza": "mesedegarri", "sinonimoak": ["lagungarri", "onuragarri", "probetxugarri"]},
  {"id": "3-170", "hitza": "mihietan", "sinonimoak": ["ahotan", "aho-mihitan", "mingainetan"]},
  {"id": "3-171", "hitza": "mihiseak", "sinonimoak": ["izarak", "maindireak"]},
  {"id": "3-172", "hitza": "mikatza", "sinonimoak": ["mingotsa", "mingarra", "karmina"]},
  {"id": "3-173", "hitza": "milika", "sinonimoak": ["mizkin", "milinga"]},
  {"id": "3-174", "hitza": "mintzagai", "sinonimoak": ["hizpide", "berbabide", "elepide"]},
  {"id": "3-175", "hitza": "mirabe", "sinonimoak": ["morroi", "otsein", "sehi"]},
  {"id": "3-176", "hitza": "mirailean", "sinonimoak": ["ispiluan"]},
  {"id": "3-177", "hitza": "moduzkotasunez", "sinonimoak": ["apaintasunez", "garbitasunez", "txukuntasunez"]},
  {"id": "3-178", "hitza": "moja", "sinonimoak": ["lekaime", "serora"]},
  {"id": "3-179", "hitza": "mokoka", "sinonimoak": ["errietan", "ika-mika", "sesioan"]},
  {"id": "3-180", "hitza": "mokordoa", "sinonimoak": ["lotsagabea", "petrala", "ozarra"]},

  /* BLOQUE 5 (181-200) */
  {"id": "3-181", "hitza": "moldatzen", "sinonimoak": ["konpontzen"]},
  {"id": "3-182", "hitza": "mordotu", "sinonimoak": ["pilatu", "metatu", "bildu"]},
  {"id": "3-183", "hitza": "motroiloa", "sinonimoak": ["potxoloa", "piporra", "zaparrotea"]},
  {"id": "3-184", "hitza": "mozkindu", "sinonimoak": ["sardakatu", "inausi", "kimatu"]},
  {"id": "3-185", "hitza": "mudakortasuna", "sinonimoak": ["ezegonkortasuna", "aldakortasuna", "aldaberatasuna"]},
  {"id": "3-186", "hitza": "mugarriak", "sinonimoak": ["zedarriak", "mugaldeak", "muturrak"]},
  {"id": "3-187", "hitza": "mukizu", "sinonimoak": ["umemoko", "umegorri", "umekondo"]},
  {"id": "3-188", "hitza": "mukuru", "sinonimoak": ["beteta", "gainezka", "lepo"]},
  {"id": "3-189", "hitza": "murriztu", "sinonimoak": ["beheratu", "merkatu", "jaitsi"]},
  {"id": "3-190", "hitza": "musu-truk", "sinonimoak": ["doan", "debalde", "urririk"]},
  {"id": "3-191", "hitza": "mutiltzen", "sinonimoak": ["lumatzen", "bipiltzen"]},
  {"id": "3-192", "hitza": "muturreko", "sinonimoak": ["ukabilko", "zartako", "ukabilkada"]},
  {"id": "3-193", "hitza": "ñabardura", "sinonimoak": ["xehetasun", "zehaztasun", "zehazkizun"]},
  {"id": "3-194", "hitza": "nabaritzen", "sinonimoak": ["nabarmetzen", "igartzen", "antzematen"]},
  {"id": "3-195", "hitza": "nabarriak", "sinonimoak": ["arreak", "arreskak", "jaspeztatuak"]},
  {"id": "3-196", "hitza": "nagikeria", "sinonimoak": ["alferkeria", "zabarkeria", "utzikeria"]},
  {"id": "3-197", "hitza": "nagusitu", "sinonimoak": ["gailendu", "garaitu", "nabarmendu"]},
  {"id": "3-198", "hitza": "nahasgarria", "sinonimoak": ["nahasian", "nahaspilatsuan", "ilunean"]},
  {"id": "3-199", "hitza": "nahikari", "sinonimoak": ["desira", "irrika", "lera"]},
  {"id": "3-200", "hitza": "nahita", "sinonimoak": ["gurata", "berariaz", "propio"]}
];