
import { WordData } from './types';

export const SYNONYMS_DATA: WordData[] = [
  { "id": "c1", "hitza": "antzeman", "sinonimoak": ["igarri", "nabaritu", "sumatu", "konturatu", "ohartu"] },
  { "id": "c2", "hitza": "izutu", "sinonimoak": ["beldurtu", "ikaratu", "kikildu", "oilotu", "koldartu"] },
  { "id": "c3", "hitza": "hizki", "sinonimoak": ["letra", "idazkera"] },
  { "id": "c4", "hitza": "ulergaitz", "sinonimoak": ["ulertezin", "adiezin ", "adigaitz"] },
  { "id": "c5", "hitza": "suspertu", "sinonimoak": ["indarberritu"] },
  { "id": "c6", "hitza": "igorri", "sinonimoak": ["bidali"] },
  { "id": "c7", "hitza": "zeken", "sinonimoak": ["esku-labur", "zikoitz", "doilor", "eskulabur"] },
  { "id": "c8", "hitza": "jakiteko grina", "sinonimoak": ["jakin-min", "jakingura", "jakin-gose", "jakin-nahi"] },
  { "id": "c9", "hitza": "are gehiago", "sinonimoak": ["areago"] },
  { "id": "c10", "hitza": "leize", "sinonimoak": ["kobazulo", "haitzulo"] },
  { "id": "c11", "hitza": "eremu", "sinonimoak": ["alor", "arlo", "esparru", "sail"] },
  { "id": "c12", "hitza": "hondar", "sinonimoak": ["harea", "hondakin"] },
  { "id": "c13", "hitza": "gauzatu", "sinonimoak": ["egin", "burutu"] },
  { "id": "c14", "hitza": "esanahia", "sinonimoak": ["esangura", "adiera", "esankizun"] },
  { "id": "c15", "hitza": "lapurtu", "sinonimoak": ["ostu", "ebatsi"] },
  { "id": "c16", "hitza": "ahaztu", "sinonimoak": ["ahantzi"] },
  { "id": "c17", "hitza": "aditzera eman", "sinonimoak": ["jakinarazi", "ezagutarazi", "adierazi"] },
  { "id": "c18", "hitza": "bestela", "sinonimoak": ["osterantzean", "gainerakoan"] },
  { "id": "c19", "hitza": "nagusitasun", "sinonimoak": ["gailentasun", "gehiagotasun"] },
  { "id": "c20", "hitza": "ukitua", "sinonimoak": ["dei"] },
  { "id": "c21", "hitza": "oinatz", "sinonimoak": ["arrasto", "aztarna"] },
  { "id": "c22", "hitza": "aztarna", "sinonimoak": ["arrasto", "oinatz"] },
  { "id": "c23", "hitza": "lohitu", "sinonimoak": ["zikindu", "likistu", "txerritu", "mantxatu"] },
  { "id": "c24", "hitza": "jazo", "sinonimoak": ["gertatu", "pasatu"] },
  { "id": "c25", "hitza": "iskanbila", "sinonimoak": ["astrapala", "zalaparta", "zarraparra"] },
  { "id": "c26", "hitza": "ikuzi", "sinonimoak": ["garbitu", "txukundu", "xahutu", "araztu"] },
  { "id": "c27", "hitza": "nabarmendu", "sinonimoak": ["nagusitu", "gailendu", "gailurtu"] },
  { "id": "c28", "hitza": "gizendu", "sinonimoak": ["loditu", "guritu", "marduldu", "galantu", "mardotu"] },
  { "id": "c29", "hitza": "sustraitu", "sinonimoak": ["errotu", "erroak bota"] },
  { "id": "c30", "hitza": "martxan jarri", "sinonimoak": ["abiarazi", "abian jarri"] },
  { "id": "c31", "hitza": "edozenbat", "sinonimoak": ["nahi beste", "nahi adina", "gura adina"] },
  { "id": "c32", "hitza": "miresmen", "sinonimoak": ["gurtza"] },
  { "id": "c33", "hitza": "entzun", "sinonimoak": ["aditu"] },
  { "id": "c34", "hitza": "ulertu", "sinonimoak": ["aditu", "jabetu"] },
  { "id": "c35", "hitza": "ezelango", "sinonimoak": ["inola"] },
  { "id": "c36", "hitza": "zaratatsua", "sinonimoak": ["arramatsu", "astrapalatsu"] },
  { "id": "c37", "hitza": "oztopoa", "sinonimoak": ["destorbu", "eragozpen", "traba"] },
  { "id": "c38", "hitza": "munstro", "sinonimoak": ["piztia"] },
  { "id": "c39", "hitza": "heldu", "sinonimoak": ["eutsi", "oratu", "lotu"] },
  { "id": "c40", "hitza": "heldu", "sinonimoak": ["iritsi", "ailegatu", "erdutu"] },
  { "id": "c41", "hitza": "hurko", "sinonimoak": ["hurbileko", "aldeko"] },
  { "id": "c42", "hitza": "kartela", "sinonimoak": ["afixa", "idazkun"] },
  { "id": "c43", "hitza": "arerioa", "sinonimoak": ["etsai", "aurkari", "izterbegi"] },
  { "id": "c44", "hitza": "suertatu", "sinonimoak": ["gertatu", "jazo"] },
  { "id": "c45", "hitza": "hurbildu", "sinonimoak": ["hurreratu", "gerturatu"] },
  { "id": "c46", "hitza": "ekidin", "sinonimoak": ["saihestu"] },
  { "id": "c47", "hitza": "atzaparra", "sinonimoak": ["erpe", "atzamar"] },
  { "id": "c48", "hitza": "seko", "sinonimoak": ["guztiz", "zeharo", "total" , "erabat"] },
  { "id": "c49", "hitza": "hanka", "sinonimoak": ["zango", "berna", "izter"] },
  { "id": "c50", "hitza": "berna", "sinonimoak": ["zangosagar", "aztal", "zangar"] },
  { "id": "c51", "hitza": "jin", "sinonimoak": ["etorri"] },
  { "id": "img1", "hitza": "zirraragarri", "sinonimoak": ["hunkigarri", "bihotz-ukigarri"], "isClass": true },
  { "id": "img2", "hitza": "alta", "sinonimoak": ["hala ere", "alabaina", "halere", "dena den"], "isClass": true },
  { "id": "img3", "hitza": "huskeria", "sinonimoak": ["ezerezkeria", "zirtzilkeria", "txikikeria", "ziztrinkeria"], "isClass": true },
  { "id": "img4", "hitza": "zorabiatu", "sinonimoak": ["alditxartu", "larritu"], "isClass": true },
  { "id": "img5", "hitza": "oka egin", "sinonimoak": ["jaurtiki", "okaztatu", "egotzi"], "isClass": true },
  { "id": "img6", "hitza": "estutu", "sinonimoak": ["zapaldu", "zanpatu"], "isClass": true },
  { "id": "img7", "hitza": "arrotz", "sinonimoak": ["bitxi", "arraro"], "isClass": true },
  { "id": "img8", "hitza": "supituki", "sinonimoak": ["bat-batean", "tupustean", "itsumustuan", "behingoan"], "isClass": true },
  { "id": "img9", "hitza": "adiera", "sinonimoak": ["zentzu", "sen"], "isClass": true },
  { "id": "img10", "hitza": "esnatu", "sinonimoak": ["itzartu", "zurtu"], "isClass": true },
  { "id": "img11", "hitza": "alditxartu", "sinonimoak": ["zorabiatu", "larritu"], "isClass": true },
  { "id": "img12", "hitza": "bakandu", "sinonimoak": ["eskastu", "urritu"], "isClass": true },
  { "id": "img13", "hitza": "erraldoi", "sinonimoak": ["jigante", "izugarri(zko)"], "isClass": true },
  { "id": "img14", "hitza": "atximur", "sinonimoak": ["imurtxi", "zimiko"], "isClass": true },
  { "id": "img15", "hitza": "jalgi", "sinonimoak": ["atera", "kaleratu"], "isClass": true },
  { "id": "img16", "hitza": "baldartu", "sinonimoak": ["trauskildu", "trakestu", "baldrestu"], "isClass": true },
  { "id": "img17", "hitza": "oldartu", "sinonimoak": ["eraso", "esetsi", "jauki"], "isClass": true },
  { "id": "img18", "hitza": "hondatu", "sinonimoak": ["suntsitu", "errautsi", "deboilatu", "erraustu"], "isClass": true },
  { "id": "img19", "hitza": "ihes", "sinonimoak": ["alde-egite", "ihesaldi"], "isClass": true },
  { "id": "img20", "hitza": "agur", "sinonimoak": ["ikusi arte", "adio", "akabo", "kilimusi"], "isClass": true },
  { "id": "img21", "hitza": "iseka", "sinonimoak": ["burlaize", "trufa", "burla", "txantxa"], "isClass": true },
  { "id": "img22", "hitza": "zorrozki", "sinonimoak": ["hertsiki", "belerazki", "hertsiro"], "isClass": true },
  { "id": "img23", "hitza": "halabeharrez", "sinonimoak": ["zoritzarrez"], "isClass": true },
  { "id": "img24", "hitza": "geldoki", "sinonimoak": ["ahul", "ahulki", "makal"], "isClass": true },
  { "id": "img25", "hitza": "jauzi", "sinonimoak": ["salto egin"], "isClass": true },
  { "id": "img26", "hitza": "bildu", "sinonimoak": ["batu", "elkartu", "batzartu"], "isClass": true },
  { "id": "img27", "hitza": "urritzen", "sinonimoak": ["gutxitu", "jaitsi", "behera egin"], "isClass": true },
  { "id": "img28", "hitza": "zapaldu", "sinonimoak": ["zanpatu", "oinkatu", "galkatu"], "isClass": true },
  { "id": "img29", "hitza": "mehartu", "sinonimoak": ["argaldu", "mehetu", "flakatu"], "isClass": true }
];
