import { WordData } from './types';

export const LEVEL_4_PART_4: WordData[] = [
  {"id": "4-301", "hitza": "urkultzen", "sinonimoak": ["aletzen", "bihitzen", "garautzen"]},
  {"id": "4-302", "hitza": "urmaelean", "sinonimoak": ["urloan", "putzuan", "istilean"]},
  {"id": "4-303", "hitza": "urpera", "sinonimoak": ["hondora", "honda", "murgilaraz"]},
  {"id": "4-304", "hitza": "urradura", "sinonimoak": ["ebakia", "zauria", "arrakala"]},
  {"id": "4-305", "hitza": "urratzen", "sinonimoak": ["hausten", "puskatzen"]},
  {"id": "4-306", "hitza": "urregorririk", "sinonimoak": ["urreirik", "dirurik", "aberastasunik"]},
  {"id": "4-307", "hitza": "urrendu", "sinonimoak": ["amaitu", "bukatu", "burutu"]},
  {"id": "4-308", "hitza": "urrikalduz", "sinonimoak": ["gupidatuz", "errukituz", "kupituz"]},
  {"id": "4-309", "hitza": "urrikoa", "sinonimoak": ["gutxikoa", "eskasekoa", "murritzekoa"]},
  {"id": "4-310", "hitza": "urripena", "sinonimoak": ["murrizketa", "lerma", "jaitsiera"]},
  {"id": "4-311", "hitza": "urrundu", "sinonimoak": ["aldendu", "urrutiratu", "lekutu"]},
  {"id": "4-312", "hitza": "urtabe", "sinonimoak": ["uztaldi", "uztaro", "urtebete"]},
  {"id": "4-313", "hitza": "urtatu", "sinonimoak": ["urtetsu", "zahar", "aspaldiko"]},
  {"id": "4-314", "hitza": "urtebetetzea", "sinonimoak": ["urtemuga", "eguna", "urteurrena"]},
  {"id": "4-315", "hitza": "urtxintxa", "sinonimoak": ["katagorri"]},
  {"id": "4-316", "hitza": "urtze-garaia", "sinonimoak": ["urtzaldia", "urtzaroa"]},
  {"id": "4-317", "hitza": "usadio", "sinonimoak": ["ohitura", "ekandu", "aztura"]},
  {"id": "4-318", "hitza": "usin", "sinonimoak": ["doministiku"]},
  {"id": "4-319", "hitza": "usnatu", "sinonimoak": ["sumatu", "aditu", "usaindu"]},
  {"id": "4-320", "hitza": "uspelduraz", "sinonimoak": ["beltzunez", "ubelduraz", "odolbatuaz"]},
  {"id": "4-321", "hitza": "uspelgune", "sinonimoak": ["laioz", "ospel"]},
  {"id": "4-322", "hitza": "ustekabean", "sinonimoak": ["ezustean", "itsumustuan", "tupustean"]},
  {"id": "4-323", "hitza": "usteltzen", "sinonimoak": ["galtzen", "hondatzen", "zapuzten"]},
  {"id": "4-324", "hitza": "ustez", "sinonimoak": ["aburuz", "iritzi", "irudiko"]},
  {"id": "4-325", "hitza": "ustiagarria", "sinonimoak": ["erabilgarria", "baliagarria", "aprobetxagarria"]},
  {"id": "4-326", "hitza": "ustiaketa", "sinonimoak": ["ustiapena", "esplotazioa", "ustiatzea"]},
  {"id": "4-327", "hitza": "usu", "sinonimoak": ["maiz", "askotan", "sarri"]},
  {"id": "4-328", "hitza": "utikan", "sinonimoak": ["alde", "ospa", "hanka"]},
  {"id": "4-329", "hitza": "uxalduko", "sinonimoak": ["zimelduko", "ihartuko", "faunduko"]},
  {"id": "4-330", "hitza": "uxatzen", "sinonimoak": ["izutzen", "ikaratzen", "beldurtzen"]},
  {"id": "4-331", "hitza": "uxterra", "sinonimoak": ["samurra", "biguna", "guria"]},
  {"id": "4-332", "hitza": "uxuka-muxuka", "sinonimoak": ["txuxtu-muxtuka", "xuxurlaka", "murmurioka"]},
  {"id": "4-333", "hitza": "uzkaili", "sinonimoak": ["irauli"]},
  {"id": "4-334", "hitza": "uzkaldurik", "sinonimoak": ["loturik", "estekaturik", "josirik"]},
  {"id": "4-335", "hitza": "uzkurtuta", "sinonimoak": ["koldartuta", "ulituta", "kikilduta"]},
  {"id": "4-336", "hitza": "uztai", "sinonimoak": ["zirrindola", "zirgilo", "obo"]},
  {"id": "4-337", "hitza": "uztardura", "sinonimoak": ["lotura", "esteka", "lokarri"]},
  {"id": "4-338", "hitza": "uztarturik", "sinonimoak": ["antxumaturik", "gurutzaturik"]},
  {"id": "4-339", "hitza": "xafarratu", "sinonimoak": ["irakuzui", "garbitu", "ikuzi"]},
  {"id": "4-340", "hitza": "xafla", "sinonimoak": ["xerra(da)", "zati", "puska"]},
  {"id": "4-341", "hitza": "xahu", "sinonimoak": ["aratz", "garbi", "lasai"]},
  {"id": "4-342", "hitza": "xahutzaileari", "sinonimoak": ["zarrastelari", "irioleari", "gastatzaileari"]},
  {"id": "4-343", "hitza": "xai", "sinonimoak": ["soto", "upategi", "biltegi"]},
  {"id": "4-344", "hitza": "xaki", "sinonimoak": ["marka", "seinale", "ezaugarri"]},
  {"id": "4-345", "hitza": "xaloa", "sinonimoak": ["atsegina", "xehea", "apala"]},
  {"id": "4-346", "hitza": "xanfarin", "sinonimoak": ["txoriburu", "nahaba", "kaskarin"]},
  {"id": "4-347", "hitza": "xantxa", "sinonimoak": ["kaikua", "ontzia", "pertza"]},
  {"id": "4-348", "hitza": "xapoka", "sinonimoak": ["pixkanaka", "apurka", "pitinka"]},
  {"id": "4-349", "hitza": "xaribaria", "sinonimoak": ["zalaparta", "azantza", "zarata"]},
  {"id": "4-350", "hitza": "xarma", "sinonimoak": ["lilura", "erakarpen", "xarmadura"]},
  {"id": "4-351", "hitza": "xatarrak", "sinonimoak": ["pixoihalak", "troxak", "haur-oihalak"]},
  {"id": "4-352", "hitza": "xauxun", "sinonimoak": ["muturluze", "sarkin", "endreda-makila"]},
  {"id": "4-353", "hitza": "xaxatuz", "sinonimoak": ["aizkatuz", "zirikatuz", "kinatuz"]},
  {"id": "4-354", "hitza": "xedatu", "sinonimoak": ["zehaztu", "adierazi", "finkatu"]},
  {"id": "4-355", "hitza": "xede", "sinonimoak": ["helburu", "asmo", "jomuga"]},
  {"id": "4-356", "hitza": "xehatu", "sinonimoak": ["txikitu", "birrindu", "zatitu"]},
  {"id": "4-357", "hitza": "xehetasunen", "sinonimoak": ["zehaztasunen", "argibideren", "azalpenen"]},
  {"id": "4-358", "hitza": "xelebreak", "sinonimoak": ["gatzdunak", "barregarriak", "txistagarriak"]},
  {"id": "4-359", "hitza": "xendra", "sinonimoak": ["bidezidor", "bidexka", "basabide"]},
  {"id": "4-360", "hitza": "xerka", "sinonimoak": ["bila", "arakatzean", "miatzean"]},
  {"id": "4-361", "hitza": "xerlotsua", "sinonimoak": ["iletsua", "ileduna", "bilotsua"]},
  {"id": "4-362", "hitza": "xextran", "sinonimoak": ["sesioan", "errietan", "kalapitan"]},
  {"id": "4-363", "hitza": "xifrialdia", "sinonimoak": ["estualdia", "larrialdia", "itolaldia"]},
  {"id": "4-364", "hitza": "xikotu", "sinonimoak": ["larrua jo", "txortan egin", "larrutan egin"]},
  {"id": "4-365", "hitza": "xildre", "sinonimoak": ["korapilo", "begizta", "begite"]},
  {"id": "4-366", "hitza": "xilintxak", "sinonimoak": ["zintzarriak", "joareak", "arranak"]},
  {"id": "4-367", "hitza": "ximena", "sinonimoak": ["apaina", "garbia", "txukuna"]},
  {"id": "4-368", "hitza": "xingilka", "sinonimoak": ["txingoka", "txingoan"]},
  {"id": "4-369", "hitza": "xingola-mingola", "sinonimoak": ["sigi-sagan", "esemeseka", "alderik alde"]},
  {"id": "4-370", "hitza": "xiringatu", "sinonimoak": ["injektatu", "txertatu", "jarri"]},
  {"id": "4-371", "hitza": "xirrika-xarraka", "sinonimoak": ["tipi-tapa", "tirriki-tarraka", "astiro-astiro"]},
  {"id": "4-372", "hitza": "xitxerra", "sinonimoak": ["txingorra", "kazkabarra", "babazuzua"]},
  {"id": "4-373", "hitza": "xixkatzea", "sinonimoak": ["iruzur egitea", "ziria sartzea", "irusako egitea"]},
  {"id": "4-374", "hitza": "xuhur", "sinonimoak": ["zeken", "eskulabur", "zikoitz"]},
  {"id": "4-375", "hitza": "xukatu", "sinonimoak": ["lehortu", "sikatu", "kendu"]},
  {"id": "4-380", "hitza": "xumea", "sinonimoak": ["xehea", "apala", "laua"]},
  {"id": "4-381", "hitza": "xuraila", "sinonimoak": ["hitsa", "zurbila", "beluria"]},
  {"id": "4-382", "hitza": "xurgatzetik", "sinonimoak": ["zurrupatzetik", "irenstetik", "hurrupatzetik"]},
  {"id": "4-383", "hitza": "xuxurla", "sinonimoak": ["marmarra", "murmurioa", "zurrumurrua"]},
  {"id": "4-384", "hitza": "zabaldiek", "sinonimoak": ["ordokiek", "lautadek", "zelaidiek"]},
  {"id": "4-385", "hitza": "zabaldu", "sinonimoak": ["hedatu", "barreiatu", "iritsi"]},
  {"id": "4-386", "hitza": "zabalera", "sinonimoak": ["hedadura", "eremua", "esparrua"]},
  {"id": "4-387", "hitza": "zabalik", "sinonimoak": ["irekirik"]},
  {"id": "4-388", "hitza": "zabaltza", "sinonimoak": ["terraza", "gaindegia", "gainaaldea"]},
  {"id": "4-389", "hitza": "zabarkeriaz", "sinonimoak": ["arduragabekeriaz", "utzikeriaz", "axolagabekeriaz"]},
  {"id": "4-390", "hitza": "zabartu", "sinonimoak": ["axolagabetu", "alfertu", "arduragabetu"]},
  {"id": "4-391", "hitza": "zabo", "sinonimoak": ["hantura", "handitu", "handitsu"]},
  {"id": "4-392", "hitza": "zaboilak", "sinonimoak": ["prakak", "galtzak"]},
  {"id": "4-393", "hitza": "zabor", "sinonimoak": ["zakar(eria)", "zarama", "hondakin"]},
  {"id": "4-394", "hitza": "zabu", "sinonimoak": ["leria", "kulunka"]},
  {"id": "4-395", "hitza": "zadora", "sinonimoak": ["kuxidadea", "nahaspila", "anabasa"]},
  {"id": "4-396", "hitza": "zaflada", "sinonimoak": ["zaplastako", "masailako", "belarrondoko"]},
  {"id": "4-397", "hitza": "zailaren", "sinonimoak": ["kikirrioaren", "armegainaren", "buztanaren"]},
  {"id": "4-398", "hitza": "zailduta", "sinonimoak": ["gogortuta", "laztuta", "zakartuta"]},
  {"id": "4-399", "hitza": "zalapartaka", "sinonimoak": ["arrapaladan", "presaka", "lasterka"]},
  {"id": "4-400", "hitza": "zaldakatu", "sinonimoak": ["lokaztu", "lohitztatu", "idoiztatu"]}
];