import { WordData } from './types';

export const LEVEL_4_PART_1: WordData[] = [
  {"id": "4-1", "hitza": "otu", "sinonimoak": ["bururatu", "gogoratu"]},
  {"id": "4-3", "hitza": "otzantzen", "sinonimoak": ["mantsozten", "hezten", "menderatzen"]},
  {"id": "4-5", "hitza": "otzara", "sinonimoak": ["saski", "otarre", "zare"]},
  {"id": "4-7", "hitza": "oztopo", "sinonimoak": ["eragozpen", "traba", "zoztor"]},
  {"id": "4-9", "hitza": "pagotxa", "sinonimoak": ["mauka", "mantxunga", "txoko"]},
  {"id": "4-11", "hitza": "pairagarri", "sinonimoak": ["jasangarri", "onargarri", "eramangarri"]},
  {"id": "4-13", "hitza": "pairu", "sinonimoak": ["egonarri", "eroapen", "pairamen"]},
  {"id": "4-15", "hitza": "paku", "sinonimoak": ["paga", "soldata", "ordainsari"]},
  {"id": "4-17", "hitza": "panpinaren", "sinonimoak": ["andrakilaren"]},
  {"id": "4-19", "hitza": "panpox", "sinonimoak": ["polit", "eder", "pinpirin"]},
  {"id": "4-21", "hitza": "papaitak", "sinonimoak": ["asmakizunak", "igarkizunak"]},
  {"id": "4-23", "hitza": "paraje", "sinonimoak": ["inguru", "leku", "txoko"]},
  {"id": "4-25", "hitza": "paratu", "sinonimoak": ["jarri", "ipini"]},
  {"id": "4-27", "hitza": "parekatu", "sinonimoak": ["erkatu", "alderatu", "konparatu"]},
  {"id": "4-29", "hitza": "pario", "sinonimoak": ["apustu", "postura", "dema"]},
  {"id": "4-31", "hitza": "pariztak", "sinonimoak": ["keinuak", "imintzioak", "inki-minkiak"]},
  {"id": "4-33", "hitza": "pasadizoak", "sinonimoak": ["istorioak", "bitxikeriak", "gertakariak"]},
  {"id": "4-35", "hitza": "pauso", "sinonimoak": ["urrats", "oinkada"]},
  {"id": "4-37", "hitza": "pegar", "sinonimoak": ["tupina", "txantxil", "suil"]},
  {"id": "4-39", "hitza": "pellokeria", "sinonimoak": ["ergelkeria", "kaikukeria", "kirtenkeria"]},
  {"id": "4-41", "hitza": "pentsakor", "sinonimoak": ["gogoetatsu", "hausnartzaile", "pentsatzailea"]},
  {"id": "4-43", "hitza": "pentzutan", "sinonimoak": ["ardurapean", "kontu", "pentzudan"]},
  {"id": "4-45", "hitza": "perkatxa", "sinonimoak": ["arretatsua", "maratza", "arduratsua"]},
  {"id": "4-47", "hitza": "perpausaren", "sinonimoak": ["esaldiaren", "esakuntzaren", "esakunearen"]},
  {"id": "4-49", "hitza": "peskizan", "sinonimoak": ["itxaropenean", "zain", "esperoan"]},
  {"id": "4-51", "hitza": "petraldu", "sinonimoak": ["txartu", "usteldu", "zaputzu"]},
  {"id": "4-53", "hitza": "pilpilka", "sinonimoak": ["pilpiraka", "taupaka", "taupadaka"]},
  {"id": "4-55", "hitza": "piltzar", "sinonimoak": ["zarpail", "pilda", "zarpa"]},
  {"id": "4-57", "hitza": "pinpirintzen", "sinonimoak": ["apaintzen", "dotoretzen", "panpinatzen"]},
  {"id": "4-59", "hitza": "pinportak", "sinonimoak": ["pikorrak", "garauak", "pikortak"]},
  {"id": "4-61", "hitza": "piper", "sinonimoak": ["sasieskola", "txikarra"]},
  {"id": "4-63", "hitza": "pisutsuak", "sinonimoak": ["astunak", "pisudunak"]},
  {"id": "4-65", "hitza": "pitinkeria", "sinonimoak": ["huskeria", "txikikeria", "zirtzileria"]},
  {"id": "4-67", "hitza": "pitzadurak", "sinonimoak": ["arrakalak", "arrailak", "artesiak"]},
  {"id": "4-69", "hitza": "piura", "sinonimoak": ["itxura", "eitea", "taxua"]},
  {"id": "4-71", "hitza": "pizgarri", "sinonimoak": ["eragingarri", "bizigarri", "akuilu"]},
  {"id": "4-73", "hitza": "piztia", "sinonimoak": ["basapiztia", "patari", "ihizi"]},
  {"id": "4-75", "hitza": "piztu", "sinonimoak": ["isiotu", "irazeki", "izeki"]},
  {"id": "4-77", "hitza": "ponitu", "sinonimoak": ["ordaindu", "pagatu", "konpondu"]},
  {"id": "4-79", "hitza": "pozgabetu", "sinonimoak": ["nahigabetu", "atsekabetu", "goibeldu"]},
  {"id": "4-81", "hitza": "prezioan", "sinonimoak": ["salneurrian"]},
  {"id": "4-83", "hitza": "programak", "sinonimoak": ["egitarauak"]},
  {"id": "4-85", "hitza": "proguzko", "sinonimoak": ["doluzko", "lutozko"]},
  {"id": "4-87", "hitza": "prometatu", "sinonimoak": ["agindu", "hitzeman", "prometsu"]},
  {"id": "4-89", "hitza": "pulunpatua", "sinonimoak": ["murgildua", "sartua", "harrapatua"]},
  {"id": "4-91", "hitza": "purrustaka", "sinonimoak": ["marmarka", "marmarioka", "sarramuskaka"]},
  {"id": "4-93", "hitza": "pusketarik", "sinonimoak": ["zatirik", "puskarik", "tatorik"]},
  {"id": "4-95", "hitza": "putzu", "sinonimoak": ["osin", "zulo", "istil"]},
  {"id": "4-97", "hitza": "puztu", "sinonimoak": ["harropuztu", "hanpatu", "harrotu"]},
  {"id": "4-99", "hitza": "sabaian", "sinonimoak": ["mandioan", "lastategian", "belartegian"]}
];