import { WordData } from './types';

export const LEVEL_3_PART_1: WordData[] = [
  /* BLOQUE 1 (1-20) */
  {"id": "3-1", "hitza": "inozokeria", "sinonimoak": ["lelokeria", "tentelkeria", "ergelkeria"]},
  {"id": "3-2", "hitza": "instituziotara", "sinonimoak": ["erakundetara"]},
  {"id": "3-3", "hitza": "intziriak", "sinonimoak": ["aieneak", "auhenak", "erostake"]},
  {"id": "3-4", "hitza": "inuritu", "sinonimoak": ["lokartu", "sorgortu", "logaletu"]},
  {"id": "3-5", "hitza": "ipini", "sinonimoak": ["jarri", "paratu"]},
  {"id": "3-6", "hitza": "ipurdikoa", "sinonimoak": ["ipurkada", "ipurdikada", "mokorkada"]},
  {"id": "3-7", "hitza": "ipurterrea", "sinonimoak": ["erretxina", "kakapirria", "triperrea"]},
  {"id": "3-8", "hitza": "irabazkin", "sinonimoak": ["mozkin", "etekin", "hobari"]},
  {"id": "3-9", "hitza": "iragaitza", "sinonimoak": ["bidea", "etorrera", "iristea"]},
  {"id": "3-10", "hitza": "iragarri", "sinonimoak": ["jakinarazi", "aditzera eman", "adierazi"]},
  {"id": "3-11", "hitza": "iraindu", "sinonimoak": ["laidotu", "laidotzatu", "laidetsi"]},
  {"id": "3-12", "hitza": "iraitz", "sinonimoak": ["bota", "egotz", "bidal"]},
  {"id": "3-13", "hitza": "iratzarri", "sinonimoak": ["esnatu", "atzarrri", "ernatu"]},
  {"id": "3-14", "hitza": "iraundor", "sinonimoak": ["etengabe", "jarraitu", "iragangaitz"]},
  {"id": "3-15", "hitza": "iraungi", "sinonimoak": ["itzali", "amatatu", "hil"]},
  {"id": "3-16", "hitza": "irekitzeko", "sinonimoak": ["zabaltzeko"]},
  {"id": "3-17", "hitza": "irigarri", "sinonimoak": ["barregarri", "lotsagarri"]},
  {"id": "3-18", "hitza": "irion", "sinonimoak": ["gastatu", "xahutu", "zarrasteldu"]},
  {"id": "3-19", "hitza": "irmotasunaz", "sinonimoak": ["sendotasunaz", "tinkotasunaz", "finkotasunaz"]},
  {"id": "3-20", "hitza": "isilean", "sinonimoak": ["ezkutuan", "sekretupean", "isilpean"]},

  /* BLOQUE 2 (21-40) */
  {"id": "3-21", "hitza": "iskanbilak", "sinonimoak": ["liskarrak", "kalapitak", "zalapartak"]},
  {"id": "3-22", "hitza": "istinga", "sinonimoak": ["lupetza", "lokatza", "basatza"]},
  {"id": "3-23", "hitza": "istorio", "sinonimoak": ["pasadizo", "kontu", "gauza"]},
  {"id": "3-24", "hitza": "itsu-itsuan", "sinonimoak": ["itsumustuka", "itsutuki", "itsuki"]},
  {"id": "3-25", "hitza": "itsukeria", "sinonimoak": ["setakeria", "egoskorkeria", "burugogorkeria"]},
  {"id": "3-26", "hitza": "itzalpea", "sinonimoak": ["gerizpea", "geriza", "itzala"]},
  {"id": "3-27", "hitza": "itzelezo", "sinonimoak": ["izugarrizko", "ikaragarrrizko", "sekulako"]},
  {"id": "3-28", "hitza": "izenburua", "sinonimoak": ["idazpurua", "titulua", "goiburukoa"]},
  {"id": "3-29", "hitza": "izenpetu", "sinonimoak": ["sinatu", "firmatu", "onartu"]},
  {"id": "3-30", "hitza": "izotzez", "sinonimoak": ["jelaz", "hormaz", "leiaz"]},
  {"id": "3-31", "hitza": "izutia", "sinonimoak": ["beldurtia", "ikaratia", "koldarra"]},
  {"id": "3-32", "hitza": "jabaldu", "sinonimoak": ["lasaitu", "baretu", "trankildu"]},
  {"id": "3-33", "hitza": "jagoten", "sinonimoak": ["zaintzen", "artatzen", "begiratzen"]},
  {"id": "3-34", "hitza": "jaiak", "sinonimoak": ["festak", "bestak"]},
  {"id": "3-35", "hitza": "jaikitzen", "sinonimoak": ["altxatzen"]},
  {"id": "3-36", "hitza": "jaioterria", "sinonimoak": ["sorterria"]},
  {"id": "3-37", "hitza": "jaitsiera", "sinonimoak": ["beheratze", "beherakada", "jaiste"]},
  {"id": "3-38", "hitza": "jaki", "sinonimoak": ["elikagai", "janari", "jangai"]},
  {"id": "3-39", "hitza": "jakin", "sinonimoak": ["zehatz", "berezi", "konkretu"]},
  {"id": "3-40", "hitza": "jakina", "sinonimoak": ["ezagun", "agerikoa", "nabaria"]},

  /* BLOQUE 3 (41-60) */
  {"id": "3-41", "hitza": "jakina", "sinonimoak": ["horixe", "noski"]},
  {"id": "3-42", "hitza": "jakitateatea", "sinonimoak": ["jakituria", "jakinduria", "jakintasuna"]},
  {"id": "3-43", "hitza": "jangalea", "sinonimoak": ["jangura", "apetitoa"]},
  {"id": "3-44", "hitza": "jantzia", "sinonimoak": ["ikasia", "jakituna", "jakintsua"]},
  {"id": "3-45", "hitza": "jantztegi", "sinonimoak": ["arropategi", "aldagela"]},
  {"id": "3-46", "hitza": "jaurti", "sinonimoak": ["bota", "egotzi", "esan"]},
  {"id": "3-47", "hitza": "jausi", "sinonimoak": ["erori"]},
  {"id": "3-48", "hitza": "jelatuta", "sinonimoak": ["izotzuta", "hormatuta", "leituta"]},
  {"id": "3-49", "hitza": "jeloskeriagatik", "sinonimoak": ["bekaizkeriagatik", "inbidiagatik", "ondamuagatik"]},
  {"id": "3-50", "hitza": "jendetasunez", "sinonimoak": ["gizalegez", "adeitasunez", "gizabidez"]},
  {"id": "3-51", "hitza": "jendetza", "sinonimoak": ["jendeketa", "jendealdia", "jende-pila"]},
  {"id": "3-52", "hitza": "jesan", "sinonimoak": ["eskatu", "galdatu", "galdegin"]},
  {"id": "3-53", "hitza": "jesartzen", "sinonimoak": ["esertzen", "ipintzen", "kokatzen"]},
  {"id": "3-54", "hitza": "jetzi", "sinonimoak": ["eraitsi", "bildu", "batu"]},
  {"id": "3-55", "hitza": "jeurt", "sinonimoak": ["atzera"]},
  {"id": "3-56", "hitza": "jipoia", "sinonimoak": ["astindua", "astinaldia", "astinketa"]},
  {"id": "3-57", "hitza": "jirabira", "sinonimoak": ["itzulinguru", "ingurumaril"]},
  {"id": "3-58", "hitza": "jiratu", "sinonimoak": ["biratu", "bihurtu", "itzuli"]},
  {"id": "3-59", "hitza": "jiten", "sinonimoak": ["etortzen", "heltzen", "iristen"]},
  {"id": "3-60", "hitza": "jitoan", "sinonimoak": ["noraezean", "bertan behera"]},

  /* BLOQUE 4 (61-80) */
  {"id": "3-61", "hitza": "joaldi", "sinonimoak": ["kontzertu", "emanaldi", "saio"]},
  {"id": "3-62", "hitza": "joera", "sinonimoak": ["jaugina", "grina", "ganua"]},
  {"id": "3-63", "hitza": "jokabidea", "sinonimoak": ["jokera", "jokamoldea", "portaera"]},
  {"id": "3-64", "hitza": "jomugara", "sinonimoak": ["helburura", "xedera"]},
  {"id": "3-65", "hitza": "jorratuko", "sinonimoak": ["landuko", "aztertuko", "ikusiko"]},
  {"id": "3-66", "hitza": "josia", "sinonimoak": ["betea", "gainezka", "goraino"]},
  {"id": "3-67", "hitza": "jostetan", "sinonimoak": ["olgetan", "jolasean", "jostaketan"]},
  {"id": "3-68", "hitza": "jujeen", "sinonimoak": ["epaileen", "jujarien"]},
  {"id": "3-69", "hitza": "jukutria", "sinonimoak": ["txandrio", "azpijoko", "azpikeria"]},
  {"id": "3-70", "hitza": "junpatzen", "sinonimoak": ["kulunkatzen", "zabunkatzen", "zarabandatzen"]},
  {"id": "3-71", "hitza": "juzgu", "sinonimoak": ["iritzi", "uste", "aburu"]},
  {"id": "3-72", "hitza": "kabartu", "sinonimoak": ["lehortu", "idortu", "sikatu"]},
  {"id": "3-73", "hitza": "kabugabea", "sinonimoak": ["amaigabea", "azkengabea", "mugagabea"]},
  {"id": "3-74", "hitza": "kadiratik", "sinonimoak": ["jarlekutik", "aulkitik", "jesarlekutik"]},
  {"id": "3-75", "hitza": "kaialdeko", "sinonimoak": ["portualdeko"]},
  {"id": "3-76", "hitza": "kailutsua", "sinonimoak": ["maskurtsua", "gogortua", "mokortua"]},
  {"id": "3-77", "hitza": "kaioak", "sinonimoak": ["antxetak", "kalatxoriak"]},
  {"id": "3-78", "hitza": "kakazkeria", "sinonimoak": ["doilorkeria", "zitalkeria", "gizatzarkeria"]},
  {"id": "3-79", "hitza": "kakaztu", "sinonimoak": ["zaputzu", "hondatu", "alferrik galdu"]},
  {"id": "3-80", "hitza": "kalte", "sinonimoak": ["gaitz", "min"]},

  /* BLOQUE 5 (81-100) */
  {"id": "3-81", "hitza": "kamutsa", "sinonimoak": ["maketsa", "lanputsa"]},
  {"id": "3-82", "hitza": "kaskutsik", "sinonimoak": ["buru hutsik"]},
  {"id": "3-83", "hitza": "katanarrua", "sinonimoak": ["diru-zorroa"]},
  {"id": "3-84", "hitza": "kebide", "sinonimoak": ["kezulo", "tximinia"]},
  {"id": "3-85", "hitza": "keinatu", "sinonimoak": ["mehatxatu", "zemaitu", "larderiatu"]},
  {"id": "3-86", "hitza": "keko-meko", "sinonimoak": ["zalantzan", "dudatsu", "ezbaian"]},
  {"id": "3-87", "hitza": "kemenez", "sinonimoak": ["gogoz", "adorez", "kalipuz"]},
  {"id": "3-88", "hitza": "kerratu", "sinonimoak": ["galdu", "mindu", "garraztu"]},
  {"id": "3-89", "hitza": "kerura", "sinonimoak": ["kiratsera", "sundara", "hatsera"]},
  {"id": "3-90", "hitza": "kexarik", "sinonimoak": ["kexurik", "arrangurarik", "ahuenik"]},
  {"id": "3-91", "hitza": "kezkatzeko", "sinonimoak": ["arduratzeko", "larritzeko", "urduritzeko"]},
  {"id": "3-92", "hitza": "kidekoak", "sinonimoak": ["antzekoak", "berdintsuak", "parekoak"]},
  {"id": "3-93", "hitza": "kikirriooa", "sinonimoak": ["zakila", "buztana", "armagia"]},
  {"id": "3-94", "hitza": "kilimon", "sinonimoak": ["porrot", "molokot", "kiebra"]},
  {"id": "3-95", "hitza": "kimatzeaz", "sinonimoak": ["inausteaz", "adaontzeaz", "mozteaz"]},
  {"id": "3-96", "hitza": "kimu", "sinonimoak": ["puja", "aldaxka", "muskil"]},
  {"id": "3-97", "hitza": "kirian", "sinonimoak": ["segidan", "ordenan", "hurrenkeran"]},
  {"id": "3-98", "hitza": "kirtenetatik", "sinonimoak": ["giderretatik", "heldulekuetatik", "eskulekuetatik"]},
  {"id": "3-99", "hitza": "kisikilkeria", "sinonimoak": ["bilaukeria", "zitalkeria", "dongekeria"]},
  {"id": "3-100", "hitza": "kitzikatu", "sinonimoak": ["berotu"]}
];