import { WordData } from './types';

export const LEVEL_2_PART_3: WordData[] = [
  /* BLOQUE 1 (201-220) */
  {"id": "2-201", "hitza": "gaixoak", "sinonimoak": ["eriak", "pazienteak"]},
  {"id": "2-202", "hitza": "gaiztotu", "sinonimoak": ["zoldu", "zornatu", "gaizkoatu"]},
  {"id": "2-203", "hitza": "galbidea", "sinonimoak": ["hondamendia", "hondamena", "galmena"]},
  {"id": "2-204", "hitza": "galdarak", "sinonimoak": ["pertzak", "eltzeak", "maskeluak"]},
  {"id": "2-205", "hitza": "galdu", "sinonimoak": ["hondatu", "mindu", "alferrik galdu"]},
  {"id": "2-206", "hitza": "gale", "sinonimoak": ["desira", "nahi", "gogo"]},
  {"id": "2-207", "hitza": "galgatu", "sinonimoak": ["balaztatu", "geldiarazi", "gelditu"]},
  {"id": "2-208", "hitza": "gaurko", "sinonimoak": ["oraingo", "egungo", "gaur egungo"]},
  {"id": "2-209", "hitza": "gazi-geza", "sinonimoak": ["gazi-gozoa", "gezamina"]},
  {"id": "2-210", "hitza": "gaztigu", "sinonimoak": ["abisu", "mezu", "jakinarazpen"]},
  {"id": "2-211", "hitza": "gela", "sinonimoak": ["areto", "sala"]},
  {"id": "2-212", "hitza": "geldiro", "sinonimoak": ["astiro", "poliki", "betaro"]},
  {"id": "2-213", "hitza": "gertaera", "sinonimoak": ["jazoera", "gertakari"]},
  {"id": "2-214", "hitza": "gibelaldean", "sinonimoak": ["atzealdean", "bizkarraldean"]},
  {"id": "2-215", "hitza": "gisako", "sinonimoak": ["moduko", "antzeko", "pareko"]},
  {"id": "2-216", "hitza": "gizen", "sinonimoak": ["lodi", "potolo", "obeso"]},
  {"id": "2-217", "hitza": "gogoangarritzat", "sinonimoak": ["oroigarritzat", "gomutagarritzat", "gogoragarritzat"]},
  {"id": "2-218", "hitza": "gogoeta", "sinonimoak": ["hausnarketa", "pentsaketa", "azterketa"]},
  {"id": "2-219", "hitza": "gogoko", "sinonimoak": ["gustuko", "atsegin", "laket"]},
  {"id": "2-220", "hitza": "goibel", "sinonimoak": ["betilun", "triste", "hits"]},

  /* BLOQUE 2 (221-240) */
  {"id": "2-221", "hitza": "goititu", "sinonimoak": ["altxatu", "jaso", "goratu"]},
  {"id": "2-222", "hitza": "gorabeherak", "sinonimoak": ["ajeak", "gaitzak", "minak"]},
  {"id": "2-223", "hitza": "gorazarre", "sinonimoak": ["omenaldi", "goraipamen", "gorespen"]},
  {"id": "2-224", "hitza": "gorputzaren", "sinonimoak": ["soinaren"]},
  {"id": "2-225", "hitza": "gorrotoa", "sinonimoak": ["herra", "higuina", "hegigoa"]},
  {"id": "2-226", "hitza": "gotzain", "sinonimoak": ["apezpiku"]},
  {"id": "2-227", "hitza": "greba", "sinonimoak": ["lanuztea", "huelga"]},
  {"id": "2-228", "hitza": "gurdi", "sinonimoak": ["orga", "karro"]},
  {"id": "2-229", "hitza": "guritzen", "sinonimoak": ["beratzen", "biguntzen", "samurtzen"]},
  {"id": "2-230", "hitza": "gutizia", "sinonimoak": ["apeta", "gurari", "nahiera"]},
  {"id": "2-231", "hitza": "gutxikoa", "sinonimoak": ["eskasekoa", "urrikoa", "txikikoa"]},
  {"id": "2-232", "hitza": "haatik", "sinonimoak": ["hala ere", "alabaina", "alta"]},
  {"id": "2-233", "hitza": "haginik", "sinonimoak": ["hortzik", "hortz-haginik", "hortzeriarik"]},
  {"id": "2-234", "hitza": "haitzulo", "sinonimoak": ["kobazulo", "leize", "harpe"]},
  {"id": "2-235", "hitza": "haizatzeko", "sinonimoak": ["aireztatzeko", "egurasteko", "airatzeko"]},
  {"id": "2-236", "hitza": "hamarkada", "sinonimoak": ["hamarraldi", "hamarte"]},
  {"id": "2-237", "hitza": "hanpatuta", "sinonimoak": ["puztuta", "handituta", "hantuta"]},
  {"id": "2-238", "hitza": "hantuste", "sinonimoak": ["harrokeria", "handikeria", "burgoikeria"]},
  {"id": "2-239", "hitza": "haranik", "sinonimoak": ["bailararik", "ibarrik", "sakanik"]},
  {"id": "2-240", "hitza": "harraskan", "sinonimoak": ["sukaltarrian", "txurrutarrian", "dalan"]},

  /* BLOQUE 3 (241-260) */
  {"id": "2-241", "hitza": "hautesten", "sinonimoak": ["aukeratzen", "hautatzen", "izendatzen"]},
  {"id": "2-242", "hitza": "heldutakoan", "sinonimoak": ["umotutakoan", "ondutakoan", "zoritutakoan"]},
  {"id": "2-243", "hitza": "herbal", "sinonimoak": ["ahul", "makal", "indarge"]},
  {"id": "2-244", "hitza": "herren", "sinonimoak": ["maingu", "trankin", "hanka-motz"]},
  {"id": "2-245", "hitza": "herrenbelak", "sinonimoak": ["akastunak", "narriodunak"]},
  {"id": "2-246", "hitza": "hertsigoa", "sinonimoak": ["itxiagoa", "estuagoa", "meharragoa"]},
  {"id": "2-247", "hitza": "hezea", "sinonimoak": ["umela", "ezkoa", "bustia"]},
  {"id": "2-248", "hitza": "higi", "sinonimoak": ["mugi"]},
  {"id": "2-249", "hitza": "hilbeila", "sinonimoak": ["gaubeila", "beila"]},
  {"id": "2-250", "hitza": "hilekoa", "sinonimoak": ["soldata", "hilerokoa", "hilabetekoa"]},
  {"id": "2-251", "hitza": "hiltzear", "sinonimoak": ["hilzorian", "hiletsian", "hiltamuan"]},
  {"id": "2-252", "hitza": "hirigunean", "sinonimoak": ["erdigunean", "erdialdean"]},
  {"id": "2-253", "hitza": "hiritarrei", "sinonimoak": ["kaletarrei", "hirikoei", "kalekoei"]},
  {"id": "2-254", "hitza": "hisitia", "sinonimoak": ["burugogorra", "setatia", "tematsua"]},
  {"id": "2-255", "hitza": "hits", "sinonimoak": ["triste", "zurbil", "goibel"]},
  {"id": "2-256", "hitza": "hitz", "sinonimoak": ["berba", "ele", "solas"]},
  {"id": "2-257", "hitza": "hitzarmen", "sinonimoak": ["itun", "akordio", "tratu"]},
  {"id": "2-258", "hitza": "hitzaurrea", "sinonimoak": ["aitzinsolasa", "sarrera", "atarikoa"]},
  {"id": "2-259", "hitza": "hitzontzia", "sinonimoak": ["hiztuna", "berritsua", "eleketaria"]},
  {"id": "2-260", "hitza": "hizketan", "sinonimoak": ["berriketan", "eleketan", "berbetan"]},

  /* BLOQUE 4 (261-280) */
  {"id": "2-261", "hitza": "hoba ez", "sinonimoak": ["jakina", "bai horixe", "ezin uka"]},
  {"id": "2-262", "hitza": "hobariekin", "sinonimoak": ["etekinekin", "mozkinekin", "irabaziekin"]},
  {"id": "2-263", "hitza": "hobenduna", "sinonimoak": ["erruduna", "egilea", "kulpaduna"]},
  {"id": "2-264", "hitza": "hobira", "sinonimoak": ["lurpera", "ehortz", "hilobira"]},
  {"id": "2-265", "hitza": "hondakin", "sinonimoak": ["zabor", "zakar", "zarama"]},
  {"id": "2-266", "hitza": "hondamena", "sinonimoak": ["hondamendia", "ausiabartza", "suntsitzea"]},
  {"id": "2-267", "hitza": "hots", "sinonimoak": ["dei", "deiadar", "kasu"]},
  {"id": "2-268", "hitza": "hunkigarria", "sinonimoak": ["zirraragarria"]},
  {"id": "2-269", "hitza": "hurkoa", "sinonimoak": ["ondokoa", "albokoa", "hurbilekoa"]},
  {"id": "2-270", "hitza": "huskeria", "sinonimoak": ["txikikeria", "ezerezkeria", "zirtzileria"]},
  {"id": "2-271", "hitza": "huts", "sinonimoak": ["kale"]},
  {"id": "2-272", "hitza": "iaioa", "sinonimoak": ["trebea", "abila", "antzetsua"]},
  {"id": "2-273", "hitza": "ibilgu", "sinonimoak": ["korridore", "pasillo"]},
  {"id": "2-274", "hitza": "idoro", "sinonimoak": ["aurkitu", "ediren", "topatu"]},
  {"id": "2-275", "hitza": "idortea", "sinonimoak": ["lehorteea", "sikatea", "agorteea"]},
  {"id": "2-276", "hitza": "igandean", "sinonimoak": ["domekan"]},
  {"id": "2-277", "hitza": "igarri", "sinonimoak": ["asmatu", "antzeman", "sumatu"]},
  {"id": "2-278", "hitza": "igorriko", "sinonimoak": ["bidaliko", "helaraziko"]},
  {"id": "2-279", "hitza": "ihardesteko", "sinonimoak": ["erantzuteko", "kontra egiteko", "trabak jartzeko"]},
  {"id": "2-280", "hitza": "ihartu", "sinonimoak": ["zimeldu", "maskaldu", "zapuztu"]},

  /* BLOQUE 5 (281-300) */
  {"id": "2-281", "hitza": "ikerketa", "sinonimoak": ["ikerkuntza", "ikertze", "ikerlan"]},
  {"id": "2-282", "hitza": "ikuskapen", "sinonimoak": ["ikuskatze", "miaketa", "araketa"]},
  {"id": "2-283", "hitza": "ikuspegi", "sinonimoak": ["panorama", "ikusmira", "bista"]},
  {"id": "2-284", "hitza": "ilemotots", "sinonimoak": ["iletxorta", "ile-txirikorda", "txirikorda"]},
  {"id": "2-285", "hitza": "ilundura", "sinonimoak": ["tristura", "nahigabe", "atsekabe"]},
  {"id": "2-286", "hitza": "iluntzean", "sinonimoak": ["ilunabarrean", "ilunsentian", "gau aldean"]},
  {"id": "2-287", "hitza": "imajina", "sinonimoak": ["eman", "jo", "pentsa"]},
  {"id": "2-288", "hitza": "imintzioka", "sinonimoak": ["keinuka"]},
  {"id": "2-289", "hitza": "inarrak", "sinonimoak": ["txinpartak", "pindarrak", "txinkak"]},
  {"id": "2-290", "hitza": "inarrosteko", "sinonimoak": ["hunkitzeko", "astintzeko", "asaldatzeko"]},
  {"id": "2-291", "hitza": "inauteriak", "sinonimoak": ["aratusteak", "inauteak"]},
  {"id": "2-292", "hitza": "indabak", "sinonimoak": ["babarrunak", "mailarrak"]},
  {"id": "2-293", "hitza": "indarkeria", "sinonimoak": ["bortxakeria", "gogorkeria", "biolentzia"]},
  {"id": "2-294", "hitza": "indartu", "sinonimoak": ["sendotu", "bizkortu", "azkartu"]},
  {"id": "2-295", "hitza": "indriska", "sinonimoak": ["euri-jasa", "zaparrada", "zaldizkoa"]},
  {"id": "2-296", "hitza": "induskatzeko", "sinonimoak": ["hondeatzeko", "zulatzeko"]},
  {"id": "2-297", "hitza": "ingumekin", "sinonimoak": ["iratxoekin"]},
  {"id": "2-298", "hitza": "injustizia", "sinonimoak": ["bidegabekeria", "zuzengabekeria"]},
  {"id": "2-299", "hitza": "inkesta", "sinonimoak": ["galdeketa", "itaunketa"]},
  {"id": "2-300", "hitza": "inoiz", "sinonimoak": ["sekula", "egundo", "nehoiz"]}
];